import * as THREE from 'three';
import {VRButton} from 'three/addons/webxr/VRButton.js';
import {XRControllerModelFactory} from 'three/addons/webxr/XRControllerModelFactory.js';

const GUNS={carbine:{name:'VX-7',mag:30,reserve:120,rate:.105,damage:34,spread:.012,reload:1.5,color:0x313943},smg:{name:'R9',mag:40,reserve:160,rate:.072,damage:24,spread:.022,reload:1.25,color:0x26303a},marksman:{name:'M12',mag:12,reserve:60,rate:.34,damage:78,spread:.004,reload:1.8,color:0x3b342d}};
const state={gun:'carbine',ammo:30,reserve:120,health:100,wave:1,cash:0,kills:0,lastShot:0,reloading:0,started:false,notice:0,snap:0,shopOpen:false};
let scene,camera,renderer,clock,player,weapon,controllerR,controllerL,gripR,gripL; const enemies=[],bullets=[],pickups=[],colliders=[]; const ray=new THREE.Raycaster(),tmp=new THREE.Vector3(),tmp2=new THREE.Vector3();
const ui={wave:document.querySelector('#wave'),objective:document.querySelector('#objective'),ammo:document.querySelector('#ammo'),cash:document.querySelector('#cash'),health:document.querySelector('#health'),notice:document.querySelector('#notice')};
document.querySelectorAll('.weapon').forEach(b=>b.onclick=()=>{document.querySelectorAll('.weapon').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.gun=b.dataset.gun});
function msg(t,s=2){ui.notice.textContent=t;ui.notice.classList.add('show');state.notice=s}
function mat(c,r=.72,m=.05){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}
function box(x,y,z,w,h,d,c){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);colliders.push(m);return m}
function init(){state.started=true;const g=GUNS[state.gun];state.ammo=g.mag;state.reserve=g.reserve;document.querySelector('#boot').style.display='none';scene=new THREE.Scene();scene.background=new THREE.Color(0x788896);scene.fog=new THREE.Fog(0x788896,20,85);camera=new THREE.PerspectiveCamera(70,innerWidth/innerHeight,.03,180);player=new THREE.Group();camera.position.y=1.65;player.add(camera);scene.add(player);player.position.set(0,0,18);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');document.body.appendChild(renderer.domElement);document.body.appendChild(VRButton.createButton(renderer,{requiredFeatures:['local-floor']}));clock=new THREE.Clock();world();controllers();desktop();spawnWave();renderer.setAnimationLoop(loop);updateUI()}
function world(){scene.add(new THREE.HemisphereLight(0xeaf6ff,0x27322c,1.6));const sun=new THREE.DirectionalLight(0xffead2,3);sun.position.set(-18,30,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-50;sun.shadow.camera.right=50;sun.shadow.camera.top=50;sun.shadow.camera.bottom=-50;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(90,90),mat(0x555b5a,1));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
for(let i=-3;i<=3;i++)box(i*11,2,-8,8,4,8,i%2?0x5d615e:0x6b6860);for(let i=-2;i<=2;i++)box(i*14,2,16,10,4,7,0x4c5357);box(-25,2,1,10,4,22,0x4f5659);box(25,2,1,10,4,22,0x4f5659);
const shop=box(-20,1.5,15,8,3,6,0x23313d);shop.userData.shop=true;const sign=new THREE.Mesh(new THREE.PlaneGeometry(5,1.2),new THREE.MeshBasicMaterial({color:0xff5e47}));sign.position.set(-20,3.7,18.02);scene.add(sign);
for(let i=0;i<18;i++){const c=new THREE.Mesh(new THREE.BoxGeometry(1.6,1.2,1.6),mat(0x3c444a));c.position.set((Math.random()-.5)*48,.6,(Math.random()-.5)*34);c.castShadow=true;c.receiveShadow=true;scene.add(c);colliders.push(c)}
weapon=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.55,.16,.16),mat(GUNS[state.gun].color,.3,.65));body.position.z=-.25;weapon.add(body);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.42,10),mat(0x161a1d,.25,.85));barrel.rotation.x=Math.PI/2;barrel.position.z=-.72;weapon.add(barrel);camera.add(weapon);weapon.position.set(.26,-.24,-.48)}
function controllers(){const f=new XRControllerModelFactory();controllerL=renderer.xr.getController(0);controllerR=renderer.xr.getController(1);gripL=renderer.xr.getControllerGrip(0);gripR=renderer.xr.getControllerGrip(1);gripL.add(f.createControllerModel(gripL));gripR.add(f.createControllerModel(gripR));player.add(controllerL,controllerR,gripL,gripR);controllerR.addEventListener('selectstart',shoot);controllerR.addEventListener('connected',e=>controllerR.userData.gp=e.data.gamepad)}
function desktop(){addEventListener('mousedown',e=>{if(e.button===0){renderer.domElement.requestPointerLock();shoot()}});addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='KeyR')reload();if(e.code==='KeyE')interact()});addEventListener('keyup',e=>keys[e.code]=0);addEventListener('mousemove',e=>{if(document.pointerLockElement){player.rotation.y-=e.movementX*.002;camera.rotation.x=THREE.MathUtils.clamp(camera.rotation.x-e.movementY*.002,-1.2,1.2)}})} const keys={};
function enemyModel(){const g=new THREE.Group(),dark=mat(0x20262b,.8),armor=mat(0x43505a,.45,.25),skin=mat(0x9a6b4d,.7);const legs=[];for(const x of [-.15,.15]){const l=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.7,4,8),dark);l.position.set(x,.55,0);g.add(l);legs.push(l)}const torso=new THREE.Mesh(new THREE.BoxGeometry(.55,.75,.28),armor);torso.position.y=1.25;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.18,14,10),skin);head.position.y=1.83;g.add(head);const rifle=new THREE.Mesh(new THREE.BoxGeometry(.65,.08,.08),dark);rifle.position.set(.25,1.25,-.25);g.add(rifle);g.userData.parts={legs,torso,head,rifle};g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
function spawnWave(){state.shopOpen=false;ui.objective.textContent='Clear the compound';const n=3+state.wave*2;for(let i=0;i<n;i++){const e=enemyModel();const a=Math.random()*Math.PI*2,r=18+Math.random()*14;e.position.set(Math.cos(a)*r,0,Math.sin(a)*r);e.userData.hp=80+state.wave*15;e.userData.speed=.8+Math.random()*.45;e.userData.cool=Math.random()*1.4;e.userData.phase=Math.random()*6;scene.add(e);enemies.push(e)}msg(`WAVE ${state.wave} — ${n} HOSTILES`,2.5)}
function shoot(){if(!state.started||state.reloading>0)return;const now=performance.now()/1000,g=GUNS[state.gun];if(now-state.lastShot<g.rate||state.ammo<=0){if(state.ammo<=0)msg('RELOAD');return}state.lastShot=now;state.ammo--;const o=new THREE.Vector3(),d=new THREE.Vector3();if(renderer.xr.isPresenting){controllerR.getWorldPosition(o);controllerR.getWorldDirection(d);d.negate()}else{camera.getWorldPosition(o);camera.getWorldDirection(d)}d.x+=(Math.random()-.5)*g.spread;d.y+=(Math.random()-.5)*g.spread;d.z+=(Math.random()-.5)*g.spread;d.normalize();ray.set(o,d);const hits=ray.intersectObjects(enemies,true);if(hits.length){let root=hits[0].object;while(root.parent&&!enemies.includes(root))root=root.parent;root.userData.hp-=g.damage*(hits[0].object===root.userData.parts?.head?1.7:1);msg('HIT',.15);if(root.userData.hp<=0)kill(root)}const tracer=new THREE.Line(new THREE.BufferGeometry().setFromPoints([o,o.clone().addScaledVector(d,40)]),new THREE.LineBasicMaterial({color:0xffc35b,transparent:true,opacity:.85}));tracer.userData.life=.06;scene.add(tracer);bullets.push(tracer);weapon.position.z=-.43;updateUI()}
function reload(){const g=GUNS[state.gun];if(state.reloading||state.ammo===g.mag||state.reserve<=0)return;state.reloading=g.reload;msg('RELOADING',g.reload)}
function finishReload(){const g=GUNS[state.gun],need=g.mag-state.ammo,t=Math.min(need,state.reserve);state.ammo+=t;state.reserve-=t;updateUI()}
function kill(e){scene.remove(e);enemies.splice(enemies.indexOf(e),1);state.kills++;state.cash+=100+state.wave*20;if(!enemies.length){state.shopOpen=true;ui.objective.textContent='Enter ARMORY and press E / trigger';msg('WAVE CLEAR — ARMORY OPEN',4)}updateUI()}
function interact(){if(!state.shopOpen)return;const p=player.position;if(p.distanceTo(new THREE.Vector3(-20,0,15))<9){const cost=250+state.wave*80;if(state.cash>=cost){state.cash-=cost;state.health=Math.min(100,state.health+35);state.reserve+=GUNS[state.gun].mag*2;state.wave++;spawnWave();msg('RESUPPLIED • NEXT WAVE',3)}else msg(`NEED $${cost}`,2)}}
function updateEnemies(dt){for(const e of enemies){e.userData.cool-=dt;e.userData.phase+=dt;tmp.copy(player.position).sub(e.position);const dist=tmp.length();tmp.y=0;tmp.normalize();if(dist>5)e.position.addScaledVector(tmp,e.userData.speed*dt);e.rotation.y=Math.atan2(tmp.x,tmp.z);const p=e.userData.parts;e.position.y=Math.sin(e.userData.phase*5)*.015;p.legs[0].rotation.x=Math.sin(e.userData.phase*8)*.45;p.legs[1].rotation.x=-p.legs[0].rotation.x;if(dist<18&&e.userData.cool<=0){e.userData.cool=.8+Math.random()*1.4;state.health-=5+state.wave*.7;msg('TAKING FIRE',.4);if(state.health<=0){state.health=100;state.cash=Math.max(0,state.cash-200);player.position.set(0,0,18);msg('REDEPLOYED',2)}updateUI()}}}
function locomotion(dt){const speed=(keys.ShiftLeft?7:4);tmp.set((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(tmp.lengthSq()){tmp.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),player.rotation.y);player.position.addScaledVector(tmp,speed*dt)}const s=renderer.xr.getSession();if(s)for(const src of s.inputSources){const a=src.gamepad?.axes;if(src.handedness==='left'&&a?.length>=4){camera.getWorldDirection(tmp);tmp.y=0;tmp.normalize();tmp2.set(1,0,0).applyQuaternion(camera.quaternion);tmp2.y=0;tmp2.normalize();player.position.addScaledVector(tmp,-(a[3]||0)*dt*3.2);player.position.addScaledVector(tmp2,(a[2]||0)*dt*3.2)}if(src.handedness==='right'&&a?.length>=4){const x=a[2]||0;if(Math.abs(x)>.75&&state.snap<=0){player.rotation.y-=Math.sign(x)*Math.PI/6;state.snap=.35}}}state.snap=Math.max(0,state.snap-dt);if(player.position.length()>42)player.position.setLength(42)}
function updateUI(){const g=GUNS[state.gun];ui.wave.textContent=`WAVE ${state.wave}`;ui.ammo.textContent=`${state.ammo} / ${state.reserve}`;ui.cash.textContent=`$${state.cash} • ${g.name}`;ui.health.style.width=`${state.health}%`;ui.health.style.background=state.health<35?'#ff5e47':'#5ce18b'}
function loop(){const dt=Math.min(clock.getDelta(),.04);if(state.reloading>0&&(state.reloading-=dt)<=0)finishReload();if(state.notice>0&&(state.notice-=dt)<=0)ui.notice.classList.remove('show');weapon.position.z=THREE.MathUtils.lerp(weapon.position.z,-.48,dt*14);locomotion(dt);updateEnemies(dt);for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.userData.life-=dt;b.material.opacity=b.userData.life/.06;if(b.userData.life<=0){scene.remove(b);bullets.splice(i,1)}}renderer.render(scene,camera)}
addEventListener('resize',()=>{if(!camera)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.querySelector('#start').onclick=init;