import * as THREE from 'three';
import {VRButton} from 'three/addons/webxr/VRButton.js';
import {XRControllerModelFactory} from 'three/addons/webxr/XRControllerModelFactory.js';

const GUNS={
 carbine:{name:'VX-7',mag:30,reserve:150,rate:.095,damage:32,spread:.010,reload:1.45,recoil:.020,color:0x313943},
 smg:{name:'R9',mag:42,reserve:210,rate:.064,damage:22,spread:.020,reload:1.18,recoil:.014,color:0x26303a},
 marksman:{name:'M12',mag:12,reserve:72,rate:.30,damage:82,spread:.003,reload:1.72,recoil:.038,color:0x3b342d}
};
const state={gun:'carbine',ammo:30,reserve:150,health:100,armor:50,wave:1,cash:0,kills:0,score:0,combo:0,comboTime:0,streak:0,lastShot:0,reloading:0,started:false,notice:0,snap:0,shopOpen:false,waveDelay:0,slowmo:0,damageFlash:0,ult:0};
let scene,camera,renderer,clock,player,weapon,controllerR,controllerL,gripR,gripL;
const enemies=[],effects=[],pickups=[],colliders=[],coverPoints=[];
const ray=new THREE.Raycaster(),tmp=new THREE.Vector3(),tmp2=new THREE.Vector3(),up=new THREE.Vector3(0,1,0),keys={};
const ui={wave:document.querySelector('#wave'),objective:document.querySelector('#objective'),ammo:document.querySelector('#ammo'),cash:document.querySelector('#cash'),health:document.querySelector('#health'),notice:document.querySelector('#notice')};
const extra=document.createElement('div');extra.id='combat-extra';extra.style.cssText='position:fixed;left:14px;bottom:18px;z-index:8;font:800 12px ui-monospace,monospace;color:#fff;text-shadow:0 2px 10px #000;pointer-events:none';document.body.appendChild(extra);
const hit=document.createElement('div');hit.style.cssText='position:fixed;inset:0;pointer-events:none;z-index:6;background:radial-gradient(circle,transparent 45%,rgba(255,40,20,.65));opacity:0';document.body.appendChild(hit);

document.querySelectorAll('.weapon').forEach(b=>b.onclick=()=>{document.querySelectorAll('.weapon').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.gun=b.dataset.gun;if(state.started)equip(state.gun)});
function msg(t,s=2){ui.notice.textContent=t;ui.notice.classList.add('show');state.notice=s}
function mat(c,r=.72,m=.05){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}
function box(x,y,z,w,h,d,c,solid=true){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;scene.add(m);if(solid)colliders.push(m);return m}
function pulse(controller,s=.5,d=45){const gp=controller?.userData?.gp,a=gp?.hapticActuators?.[0]||gp?.vibrationActuator;try{a?.pulse?.(s,d)}catch{}}
function tone(f=180,d=.05,v=.025){try{const c=tone.c||(tone.c=new AudioContext()),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(v,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d)}catch{}}

function init(){state.started=true;document.querySelector('#boot').style.display='none';scene=new THREE.Scene();scene.background=new THREE.Color(0x6f7f8c);scene.fog=new THREE.Fog(0x6f7f8c,18,88);camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.03,180);player=new THREE.Group();camera.position.y=1.65;player.add(camera);scene.add(player);player.position.set(0,0,20);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');document.body.appendChild(renderer.domElement);document.body.appendChild(VRButton.createButton(renderer,{requiredFeatures:['local-floor'],optionalFeatures:['bounded-floor','hand-tracking']}));clock=new THREE.Clock();world();controllers();desktop();equip(state.gun);spawnWave();renderer.setAnimationLoop(loop);updateUI()}
function world(){scene.add(new THREE.HemisphereLight(0xeaf6ff,0x27322c,1.5));const sun=new THREE.DirectionalLight(0xffead2,3.2);sun.position.set(-18,30,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-50;sun.shadow.camera.right=50;sun.shadow.camera.top=50;sun.shadow.camera.bottom=-50;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(94,94),mat(0x535b5b,1));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
 for(let i=-3;i<=3;i++){const b=box(i*11,2,-8,8,4,8,i%2?0x59615e:0x696860);door(b,i*11,0,-3.96)}for(let i=-2;i<=2;i++)box(i*14,2,16,10,4,7,0x485157);box(-25,2,1,10,4,22,0x4b5356);box(25,2,1,10,4,22,0x4b5356);
 const shop=box(-20,1.5,15,8,3,6,0x21313d);shop.userData.shop=true;const sign=new THREE.Mesh(new THREE.PlaneGeometry(5,1.2),new THREE.MeshBasicMaterial({color:0xff5e47}));sign.position.set(-20,3.7,18.02);scene.add(sign);
 for(let i=0;i<24;i++){const c=new THREE.Mesh(new THREE.BoxGeometry(1.5+Math.random(),1+Math.random(),1.5+Math.random()),mat(0x39434a));c.position.set((Math.random()-.5)*52,c.geometry.parameters.height/2,(Math.random()-.5)*38);c.castShadow=c.receiveShadow=true;scene.add(c);colliders.push(c);coverPoints.push(c.position.clone())}
 for(const p of [[0,0,0],[18,0,-18],[-17,0,-15],[16,0,14]]){const ring=new THREE.Mesh(new THREE.TorusGeometry(1.1,.08,8,28),new THREE.MeshBasicMaterial({color:0x4ce7ff}));ring.rotation.x=Math.PI/2;ring.position.set(...p);ring.position.y=.05;scene.add(ring)}
}
function door(building,x,y,z){const d=new THREE.Mesh(new THREE.BoxGeometry(2.2,2.7,.2),mat(0x20262b));d.position.set(x,1.35,z);scene.add(d)}
function equip(id){const g=GUNS[id];state.gun=id;state.ammo=Math.min(state.ammo||g.mag,g.mag);state.reserve=Math.max(state.reserve||0,g.reserve);if(weapon)weapon.removeFromParent();weapon=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.58,.17,.18),mat(g.color,.28,.7));body.position.z=-.28;weapon.add(body);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.024,.034,.46,10),mat(0x111619,.22,.9));barrel.rotation.x=Math.PI/2;barrel.position.z=-.76;weapon.add(barrel);const sight=new THREE.Mesh(new THREE.BoxGeometry(.08,.07,.13),mat(0x171d20,.3,.7));sight.position.set(0,.12,-.36);weapon.add(sight);camera.add(weapon);weapon.position.set(.26,-.24,-.48);updateUI()}
function controllers(){const f=new XRControllerModelFactory();controllerL=renderer.xr.getController(0);controllerR=renderer.xr.getController(1);gripL=renderer.xr.getControllerGrip(0);gripR=renderer.xr.getControllerGrip(1);gripL.add(f.createControllerModel(gripL));gripR.add(f.createControllerModel(gripR));player.add(controllerL,controllerR,gripL,gripR);controllerR.addEventListener('selectstart',shoot);controllerR.addEventListener('squeezestart',reload);controllerL.addEventListener('selectstart',interact);for(const c of [controllerL,controllerR])c.addEventListener('connected',e=>c.userData.gp=e.data.gamepad)}
function desktop(){addEventListener('mousedown',e=>{if(e.button===0){renderer.domElement.requestPointerLock();shoot()}if(e.button===2)state.ult=1});addEventListener('mouseup',e=>{if(e.button===2)state.ult=0});addEventListener('contextmenu',e=>e.preventDefault());addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='KeyR')reload();if(e.code==='KeyE')interact();if(e.code==='Digit1')equip('carbine');if(e.code==='Digit2')equip('smg');if(e.code==='Digit3')equip('marksman')});addEventListener('keyup',e=>keys[e.code]=0);addEventListener('mousemove',e=>{if(document.pointerLockElement){player.rotation.y-=e.movementX*.002;camera.rotation.x=THREE.MathUtils.clamp(camera.rotation.x-e.movementY*.002,-1.2,1.2)}})}
function enemyModel(type='rifle'){const g=new THREE.Group(),dark=mat(0x20262b,.8),armor=mat(type==='elite'?0x7d2830:type==='rusher'?0x5e4b27:0x43505a,.42,.28),skin=mat(0x9a6b4d,.7),legs=[];for(const x of [-.15,.15]){const l=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.7,4,8),dark);l.position.set(x,.55,0);g.add(l);legs.push(l)}const torso=new THREE.Mesh(new THREE.BoxGeometry(.55,.75,.28),armor);torso.position.y=1.25;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.18,14,10),skin);head.position.y=1.83;g.add(head);const rifle=new THREE.Mesh(new THREE.BoxGeometry(.65,.08,.08),dark);rifle.position.set(.25,1.25,-.25);g.add(rifle);g.userData.parts={legs,torso,head,rifle};g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
function spawnEnemy(type,i){const e=enemyModel(type),a=Math.random()*Math.PI*2,r=20+Math.random()*16;e.position.set(Math.cos(a)*r,0,Math.sin(a)*r);const mult=type==='elite'?2.4:type==='rusher'?.8:1;e.userData={type,hp:(85+state.wave*16)*mult,maxHp:(85+state.wave*16)*mult,speed:(type==='rusher'?2.15:type==='elite'?.7:1.0)+Math.random()*.35,cool:Math.random()*1.3,phase:Math.random()*6,strafe:Math.random()<.5?-1:1,cover:null,flinch:0};scene.add(e);enemies.push(e)}
function spawnWave(){state.shopOpen=false;state.waveDelay=0;ui.objective.textContent=state.wave%5===0?'ELIMINATE THE COMMANDER':'Clear the compound';const n=4+state.wave*2;for(let i=0;i<n;i++)spawnEnemy(state.wave%5===0&&i===0?'elite':i%4===0?'rusher':'rifle',i);msg(state.wave%5===0?`BOSS WAVE ${state.wave}`:`WAVE ${state.wave} — ${n} HOSTILES`,2.5)}
function shoot(){if(!state.started||state.reloading>0)return;const now=performance.now()/1000,g=GUNS[state.gun];if(now-state.lastShot<g.rate||state.ammo<=0){if(state.ammo<=0)msg('RELOAD');return}state.lastShot=now;state.ammo--;const o=new THREE.Vector3(),d=new THREE.Vector3();if(renderer.xr.isPresenting){controllerR.getWorldPosition(o);controllerR.getWorldDirection(d).negate()}else{camera.getWorldPosition(o);camera.getWorldDirection(d)}const focus=state.ult?0.35:1;d.x+=(Math.random()-.5)*g.spread*focus;d.y+=(Math.random()-.5)*g.spread*focus;d.z+=(Math.random()-.5)*g.spread*focus;d.normalize();ray.set(o,d);const hits=ray.intersectObjects(enemies,true);if(hits.length){let root=hits[0].object;while(root.parent&&!enemies.includes(root))root=root.parent;const headshot=hits[0].object===root.userData.parts?.head;root.userData.hp-=g.damage*(headshot?1.9:1);root.userData.flinch=.18;state.score+=headshot?75:25;msg(headshot?'HEADSHOT':'HIT',.16);if(root.userData.hp<=0)kill(root,headshot)}tracer(o,d,g);weapon.position.z=-.40;weapon.rotation.x=-g.recoil;pulse(controllerR,.28,30);tone(state.gun==='marksman'?110:160,.035,.018);updateUI()}
function tracer(o,d,g){const end=o.clone().addScaledVector(d,46),mid=o.clone().lerp(end,.5);mid.y-=.08;const curve=new THREE.QuadraticBezierCurve3(o,mid,end),line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(12)),new THREE.LineBasicMaterial({color:state.gun==='marksman'?0xffe2a1:0xffb64d,transparent:true,opacity:.9}));line.userData.life=.07;scene.add(line);effects.push(line)}
function reload(){const g=GUNS[state.gun];if(state.reloading||state.ammo===g.mag||state.reserve<=0)return;state.reloading=g.reload;msg('RELOADING',g.reload);pulse(controllerR,.18,70)}
function finishReload(){const g=GUNS[state.gun],need=g.mag-state.ammo,t=Math.min(need,state.reserve);state.ammo+=t;state.reserve-=t;updateUI()}
function kill(e,headshot=false){scene.remove(e);enemies.splice(enemies.indexOf(e),1);state.kills++;state.streak++;state.combo++;state.comboTime=3.5;const bonus=Math.min(5,state.combo);state.cash+=100+state.wave*22+(headshot?60:0);state.score+=Math.round((100+(headshot?100:0))*bonus);if(state.streak%5===0){state.health=Math.min(100,state.health+15);state.armor=Math.min(100,state.armor+15);msg(`${state.streak} KILL STREAK • FIELD RECOVERY`,2)}if(Math.random()<.22)spawnPickup(e.position);if(!enemies.length){state.shopOpen=true;ui.objective.textContent='Enter ARMORY and interact';msg('WAVE CLEAR — ARMORY OPEN',4)}updateUI()}
function spawnPickup(pos){const type=Math.random()<.5?'med':'ammo',p=new THREE.Mesh(new THREE.OctahedronGeometry(.28),new THREE.MeshStandardMaterial({color:type==='med'?0x59e38c:0x5bbdff,emissive:type==='med'?0x163b25:0x12304a,emissiveIntensity:1.4}));p.position.copy(pos);p.position.y=.55;p.userData={type,phase:Math.random()*6.2};scene.add(p);pickups.push(p)}
function interact(){if(!state.shopOpen)return;const p=player.position;if(p.distanceTo(new THREE.Vector3(-20,0,15))<9){const cost=220+state.wave*70;if(state.cash>=cost){state.cash-=cost;state.health=100;state.armor=Math.min(100,state.armor+35);state.reserve+=GUNS[state.gun].mag*3;state.wave++;spawnWave();msg('FULL RESUPPLY • NEXT WAVE',3)}else msg(`NEED $${cost}`,2)}}
function damage(n){let remain=n;if(state.armor>0){const a=Math.min(state.armor,n*.7);state.armor-=a;remain-=a}state.health-=remain;state.damageFlash=.18;hit.style.opacity=.75;pulse(controllerL,.45,65);if(state.health<=0){state.health=100;state.armor=35;state.cash=Math.max(0,state.cash-200);state.combo=0;state.streak=0;player.position.set(0,0,20);msg('REDEPLOYED',2)}updateUI()}
function updateEnemies(dt){for(const e of enemies){e.userData.cool-=dt;e.userData.phase+=dt;e.userData.flinch=Math.max(0,e.userData.flinch-dt);tmp.copy(player.position).sub(e.position);const dist=tmp.length();tmp.y=0;tmp.normalize();const side=tmp2.crossVectors(up,tmp).multiplyScalar(e.userData.strafe);if(e.userData.type==='rusher'){if(dist>2.2)e.position.addScaledVector(tmp,e.userData.speed*dt);if(dist<2.8&&e.userData.cool<=0){e.userData.cool=.7;damage(12+state.wave*.6)}}else{if(dist>11)e.position.addScaledVector(tmp,e.userData.speed*dt);else if(dist<6)e.position.addScaledVector(tmp,-e.userData.speed*.6*dt);e.position.addScaledVector(side,Math.sin(e.userData.phase*1.8)*dt*.55);if(dist<24&&e.userData.cool<=0){e.userData.cool=(e.userData.type==='elite'?.45:.8)+Math.random()*1.1;const accuracy=Math.max(.35,.78-dist*.015);if(Math.random()<accuracy)damage((e.userData.type==='elite'?9:5)+state.wave*.55)}}e.rotation.y=Math.atan2(tmp.x,tmp.z);const p=e.userData.parts;e.position.y=Math.sin(e.userData.phase*5)*.012;p.legs[0].rotation.x=Math.sin(e.userData.phase*8)*.42;p.legs[1].rotation.x=-p.legs[0].rotation.x;e.rotation.z=e.userData.flinch?Math.sin(e.userData.phase*30)*.08:0}}
function locomotion(dt){const speed=(keys.ShiftLeft?7.2:4.2);tmp.set((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(tmp.lengthSq()){tmp.normalize().applyAxisAngle(up,player.rotation.y);player.position.addScaledVector(tmp,speed*dt)}const s=renderer.xr.getSession();if(s)for(const src of s.inputSources){const a=src.gamepad?.axes;if(src.handedness==='left'&&a?.length>=4){camera.getWorldDirection(tmp);tmp.y=0;tmp.normalize();tmp2.set(1,0,0).applyQuaternion(camera.quaternion);tmp2.y=0;tmp2.normalize();player.position.addScaledVector(tmp,-(a[3]||0)*dt*3.5);player.position.addScaledVector(tmp2,(a[2]||0)*dt*3.5)}if(src.handedness==='right'&&a?.length>=4){const x=a[2]||0;if(Math.abs(x)>.75&&state.snap<=0){player.rotation.y-=Math.sign(x)*Math.PI/6;state.snap=.35}}}state.snap=Math.max(0,state.snap-dt);if(player.position.length()>43)player.position.setLength(43)}
function updatePickups(dt){for(let i=pickups.length-1;i>=0;i--){const p=pickups[i];p.userData.phase+=dt;p.rotation.y+=dt*2;p.position.y=.55+Math.sin(p.userData.phase*3)*.12;if(p.position.distanceTo(player.position)<1.5){if(p.userData.type==='med')state.health=Math.min(100,state.health+30);else state.reserve+=GUNS[state.gun].mag;msg(p.userData.type==='med'?'MEDKIT +30':'AMMO ACQUIRED',1);scene.remove(p);pickups.splice(i,1);updateUI()}}}
function updateUI(){const g=GUNS[state.gun];ui.wave.textContent=`WAVE ${state.wave}`;ui.ammo.textContent=`${state.ammo} / ${state.reserve}`;ui.cash.textContent=`$${state.cash} • ${g.name}`;ui.health.style.width=`${Math.max(0,state.health)}%`;ui.health.style.background=state.health<35?'#ff5e47':'#5ce18b';extra.innerHTML=`ARMOR ${Math.round(state.armor)} • SCORE ${state.score}<br>STREAK ${state.streak}${state.combo>1?` • COMBO x${Math.min(5,state.combo)}`:''}`}
function loop(){let dt=Math.min(clock.getDelta(),.04);if(state.ult)dt*=.72;if(state.reloading>0&&(state.reloading-=dt)<=0)finishReload();if(state.notice>0&&(state.notice-=dt)<=0)ui.notice.classList.remove('show');if(state.comboTime>0&&(state.comboTime-=dt)<=0)state.combo=0;if(state.damageFlash>0){state.damageFlash-=dt;hit.style.opacity=Math.max(0,state.damageFlash*4)}weapon.position.z=THREE.MathUtils.lerp(weapon.position.z,-.48,dt*14);weapon.rotation.x=THREE.MathUtils.lerp(weapon.rotation.x,0,dt*16);locomotion(dt);updateEnemies(dt);updatePickups(dt);for(let i=effects.length-1;i>=0;i--){const b=effects[i];b.userData.life-=dt;b.material.opacity=Math.max(0,b.userData.life/.07);if(b.userData.life<=0){scene.remove(b);effects.splice(i,1)}}renderer.render(scene,camera)}
addEventListener('resize',()=>{if(!camera)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});document.querySelector('#start').onclick=init;