#!/usr/bin/env python3
"""
Rate-Limited Reverse Proxy — forwards every request to a backend URL, enforcing
a per-client token-bucket rate limit (429 once exhausted). Generated by the
Aether Worker Foundry. Stdlib only (http.server).
"""
from __future__ import annotations
import argparse, threading, time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urljoin
import urllib.request
import urllib.error


class Bucket:
    def __init__(self, rate_per_s, burst):
        self.rate, self.burst = rate_per_s, burst
        self.tokens, self.t = burst, time.time()
        self.lock = threading.Lock()

    def take(self):
        with self.lock:
            now = time.time()
            self.tokens = min(self.burst, self.tokens + (now - self.t) * self.rate)
            self.t = now
            if self.tokens >= 1:
                self.tokens -= 1
                return True
            return False


def make_handler(backend, buckets, rate, burst):
    class Handler(BaseHTTPRequestHandler):
        def log_message(self, *a):
            pass

        def _proxy(self):
            client = self.client_address[0]
            b = buckets.setdefault(client, Bucket(rate, burst))
            if not b.take():
                self.send_response(429)
                self.send_header("Retry-After", "1")
                self.end_headers()
                self.wfile.write(b"rate limit exceeded")
                return
            length = int(self.headers.get("Content-Length", 0) or 0)
            body = self.rfile.read(length) if length else None
            url = urljoin(backend, self.path)
            req = urllib.request.Request(url, data=body, method=self.command)
            for k, v in self.headers.items():
                if k.lower() not in ("host", "content-length"):
                    req.add_header(k, v)
            try:
                with urllib.request.urlopen(req, timeout=30) as r:
                    self.send_response(r.status)
                    for k, v in r.getheaders():
                        if k.lower() not in ("transfer-encoding", "connection"):
                            self.send_header(k, v)
                    self.end_headers()
                    self.wfile.write(r.read())
            except urllib.error.HTTPError as e:
                self.send_response(e.code)
                self.end_headers()
                self.wfile.write(e.read())
            except Exception as e:
                self.send_response(502)
                self.end_headers()
                self.wfile.write(str(e).encode())

        do_GET = do_POST = do_PUT = do_DELETE = do_PATCH = _proxy

    return Handler


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--port", type=int, default={{PORT}})
    ap.add_argument("--backend", default="{{BACKEND}}")
    ap.add_argument("--rate", type=float, default={{RATE}})
    ap.add_argument("--burst", type=int, default=20)
    a = ap.parse_args()
    buckets: dict = {}
    srv = ThreadingHTTPServer(("0.0.0.0", a.port), make_handler(a.backend, buckets, a.rate, a.burst))
    print(f"[rate-limited-proxy] :{a.port} -> {a.backend}  ({a.rate} req/s per client, burst {a.burst})")
    srv.serve_forever()


if __name__ == "__main__":
    main()
