#!/usr/bin/env node
/**
 * PDF Renderer — headless Chromium via Playwright. Loads each URL and prints
 * it to a PDF file. Generated by the Aether Worker Foundry.
 *
 *   npm i playwright   # once
 *   node pdf.js --urls https://a.com,https://b.com --outdir ./pdfs
 */
'use strict';
const fs = require('fs');
const path = require('path');

function arg(name, def) {
  const i = process.argv.indexOf('--' + name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

async function launch(chromium) {
  try { return await chromium.launch({ headless: true }); }
  catch (e) {
    const exe = process.env.PLAYWRIGHT_CHROMIUM || '/opt/pw-browsers/chromium';
    return await chromium.launch({ headless: true, executablePath: exe });
  }
}

(async () => {
  const { chromium } = require('playwright');
  const urls = arg('urls', '{{URLS}}').split(',').map(s => s.trim()).filter(Boolean);
  const format = arg('format', '{{FORMAT}}');
  const outdir = arg('outdir', '{{OUTDIR}}');
  fs.mkdirSync(outdir, { recursive: true });

  const browser = await launch(chromium);
  const ctx = await browser.newContext();
  for (const url of urls) {
    const page = await ctx.newPage();
    try {
      await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
      const name = url.replace(/[^a-z0-9]+/gi, '_').slice(0, 80) + '.pdf';
      const file = path.join(outdir, name);
      await page.pdf({ path: file, format, printBackground: true });
      console.log(JSON.stringify({ url, ok: true, file }));
    } catch (e) {
      console.log(JSON.stringify({ url, ok: false, error: String(e.message || e) }));
    } finally {
      await page.close();
    }
  }
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
