#!/usr/bin/env python3
"""
Price Tracker — fetches page(s) on an interval, pulls a price out of the raw
HTML with a regex, and fires a webhook only when the price changes. No browser
needed (works against server-rendered price text). Generated by the Aether
Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, re, sys, time
import urllib.request


def fetch_price(url, pattern, timeout):
    req = urllib.request.Request(url, headers={"User-Agent": "AetherPriceTracker/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        html = r.read(2_000_000).decode("utf-8", "replace")
    m = re.search(pattern, html)
    if not m:
        return None
    raw = m.group(1) if m.groups() else m.group(0)
    cleaned = re.sub(r"[^0-9.]", "", raw)
    try:
        return float(cleaned)
    except ValueError:
        return None


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--urls", default="{{URLS}}")
    ap.add_argument("--pattern", default="{{PRICE_REGEX}}")
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--webhook", default="{{WEBHOOK}}")
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()
    urls = [u.strip() for u in a.urls.split(",") if u.strip()]
    last: dict = {}
    while True:
        for u in urls:
            try:
                price = fetch_price(u, a.pattern, 20)
            except Exception as e:
                print(json.dumps({"url": u, "error": str(e)}), file=sys.stderr)
                continue
            if price is None:
                print(json.dumps({"url": u, "warning": "pattern did not match"}), file=sys.stderr)
                continue
            prev = last.get(u)
            rec = {"url": u, "price": price, "ts": time.time()}
            if prev is not None and prev != price:
                rec["was"] = prev
                rec["delta"] = round(price - prev, 4)
                print(json.dumps(rec)); sys.stdout.flush()
                if a.webhook:
                    try: post(a.webhook, rec)
                    except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
            elif prev is None:
                print(json.dumps({**rec, "baseline": True}))
            last[u] = price
        if a.once:
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
