#!/usr/bin/env python3
"""
API Poller — polls a JSON REST endpoint that returns a list of records on an
interval, diffs against the previous poll by a key field, and emits only
added/removed/changed records. Generated by the Aether Worker Foundry. Stdlib
only.
"""
from __future__ import annotations
import argparse, json, sys, time
import urllib.request


def fetch(url, timeout):
    req = urllib.request.Request(url, headers={"User-Agent": "AetherAPIPoller/1.0", "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        data = json.loads(r.read())
    if isinstance(data, dict):
        for v in data.values():
            if isinstance(v, list):
                return v
        return [data]
    return data


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default="{{URL}}")
    ap.add_argument("--key", default="{{KEY}}")
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--webhook", default="{{WEBHOOK}}")
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()

    prev: dict = {}
    first = True
    while True:
        try:
            rows = fetch(a.url, 20)
        except Exception as e:
            print(json.dumps({"error": str(e)}), file=sys.stderr)
            if a.once:
                break
            time.sleep(a.interval); continue

        cur = {str(r.get(a.key, i)): r for i, r in enumerate(rows)}
        if not first:
            for k, v in cur.items():
                if k not in prev:
                    ev = {"event": "added", "key": k, "record": v}
                    print(json.dumps(ev)); sys.stdout.flush()
                    if a.webhook:
                        try: post(a.webhook, ev)
                        except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
                elif prev[k] != v:
                    ev = {"event": "changed", "key": k, "before": prev[k], "after": v}
                    print(json.dumps(ev)); sys.stdout.flush()
                    if a.webhook:
                        try: post(a.webhook, ev)
                        except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
            for k in prev:
                if k not in cur:
                    ev = {"event": "removed", "key": k, "record": prev[k]}
                    print(json.dumps(ev)); sys.stdout.flush()
                    if a.webhook:
                        try: post(a.webhook, ev)
                        except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
        else:
            print(json.dumps({"event": "baseline", "n": len(cur)}), file=sys.stderr)
        prev = cur
        first = False
        if a.once:
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
