#!/usr/bin/env python3
"""
Prometheus Metrics Scraper — scrapes /metrics endpoints on an interval, parses
the exposition format into samples, and (optionally) POSTs selected series to a
sink. Generated by the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, sys, time
import urllib.request

_LINE = None


def parse_metrics(text):
    """Yield {name, labels, value} for each non-comment sample line."""
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            left, value = line.rsplit(" ", 1)
            val = float(value)
        except ValueError:
            continue
        if "{" in left:
            name, lbl = left.split("{", 1)
            labels = {}
            for pair in lbl.rstrip("}").split(","):
                if "=" in pair:
                    k, v = pair.split("=", 1)
                    labels[k.strip()] = v.strip().strip('"')
        else:
            name, labels = left, {}
        yield {"name": name.strip(), "labels": labels, "value": val}


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--targets", default="{{TARGETS}}")
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--sink", default="{{SINK}}")
    ap.add_argument("--match", default="", help="only keep series whose name contains this")
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()
    targets = [t.strip() for t in a.targets.split(",") if t.strip()]

    while True:
        for tgt in targets:
            try:
                with urllib.request.urlopen(tgt, timeout=15) as r:
                    samples = [s for s in parse_metrics(r.read().decode("utf-8", "replace"))
                               if a.match in s["name"]]
            except Exception as e:
                print(json.dumps({"target": tgt, "error": str(e)}), file=sys.stderr); continue
            out = {"target": tgt, "ts": time.time(), "count": len(samples), "samples": samples}
            print(json.dumps({"target": tgt, "count": len(samples)})); sys.stdout.flush()
            if a.sink:
                try: post(a.sink, out)
                except Exception as e: print(json.dumps({"sink_error": str(e)}), file=sys.stderr)
        if a.once:
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
