/**
 * Worker Foundry — JS engine for the Cloudflare Pages / desktop transports.
 * ═══════════════════════════════════════════════════════════════════════
 *
 * The Python Foundry (aether_platform/foundry) is the source of truth for the
 * 20 templates. `gen_foundry_bundle.py` freezes its manifest + template files
 * into `foundry_bundle.js`, which this module reads — so the Foundry tab works
 * on Cloudflare Workers and the desktop server (which can't call Python),
 * without maintaining the templates twice.
 *
 * Rendering (token substitution, generated README.md + run.sh) matches the
 * Python engine byte-for-byte, verified by test_foundry_js.js. The ZIP writer
 * is a dependency-free "stored" (uncompressed) packer so downloads work in any
 * JS runtime with no libraries.
 */
'use strict';

const BUNDLE = require('./foundry_bundle.js');

const TOKEN = /\{\{([A-Z0-9_]+)\}\}/g;

function listTemplates() {
  return BUNDLE.manifest.templates.map((t) => ({
    id: t.id, name: t.name, category: t.category, runtime: t.runtime,
    summary: t.summary, params: t.params || [], needs: t.needs || [],
    run: t.run || '', entry: t.entry,
  }));
}

function categories() {
  return BUNDLE.manifest.categories || [];
}

function getTemplate(id) {
  const t = BUNDLE.manifest.templates.find((x) => x.id === id);
  if (!t) throw new Error(`unknown template: ${id}`);
  return t;
}

function resolveParams(t, params) {
  params = params || {};
  const out = {}; // insertion order = manifest param order (matches Python)
  for (const spec of t.params || []) {
    const v = Object.prototype.hasOwnProperty.call(params, spec.name)
      ? params[spec.name] : (spec.default ?? '');
    out[spec.name] = v == null ? '' : String(v);
  }
  return out;
}

function substitute(text, resolved) {
  return text.replace(TOKEN, (m, key) =>
    Object.prototype.hasOwnProperty.call(resolved, key) ? resolved[key] : m);
}

function templateFiles(t) {
  // Pull "<id>/<relpath>" entries from the bundle, keyed by relpath.
  const prefix = t.id + '/';
  const files = {};
  for (const [k, v] of Object.entries(BUNDLE.files)) {
    if (k.startsWith(prefix)) files[k.slice(prefix.length)] = v;
  }
  return files;
}

function readme(t, params) {
  const lines = [
    `# ${t.name}`, '',
    t.summary, '',
    `- **Category:** ${t.category}`,
    `- **Runtime:** ${t.runtime}`,
    `- **Generated by:** Aether Worker Foundry`, '',
    '## Run', '', '```bash', t.run || '', '```', '',
  ];
  const keys = Object.keys(params);
  if (keys.length) {
    lines.push('## Baked-in parameters', '',
      'These are the defaults compiled into the file; every one is also a '
      + 'CLI flag (`--lower-kebab-name`) you can override at run time.', '');
    for (const k of keys) lines.push(`- \`${k}\` = \`${params[k] || '(empty)'}\``);
    lines.push('');
  }
  const needs = t.needs || [];
  if (needs.length) {
    lines.push('## Requirements', '');
    for (const n of needs) lines.push(`- ${n}`);
    lines.push('');
  }
  lines.push('---', '',
    'Regenerate or customize this worker any time from the Aether console '
    + '(Foundry tab) or by asking Claude in the Worker Studio.');
  return lines.join('\n');
}

function runScript(t) {
  let pre = '#!/usr/bin/env bash\nset -euo pipefail\ncd "$(dirname "$0")"\n\n';
  if (t.runtime === 'node') {
    pre += "command -v node >/dev/null || { echo 'Node.js required'; exit 1; }\n";
    pre += '[ -d node_modules ] || npm i playwright\n';
  } else {
    pre += "command -v python3 >/dev/null || { echo 'python3 required'; exit 1; }\n";
  }
  return pre + (t.run || '') + '\n';
}

function render(templateId, params) {
  const t = getTemplate(templateId);
  const resolved = resolveParams(t, params);
  const raw = templateFiles(t);
  const files = {};
  for (const [path, body] of Object.entries(raw)) files[path] = substitute(body, resolved);
  files['README.md'] = readme(t, resolved);
  files['run.sh'] = runScript(t);
  return {
    template_id: t.id, name: t.name, entry: t.entry, runtime: t.runtime,
    run: t.run || '', params: resolved, files,
  };
}

// ── minimal dependency-free ZIP (stored / no compression) ───────────────
const _CRC_TABLE = (() => {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
    table[n] = c >>> 0;
  }
  return table;
})();

function crc32(bytes) {
  let c = 0xFFFFFFFF;
  for (let i = 0; i < bytes.length; i++) c = _CRC_TABLE[(c ^ bytes[i]) & 0xFF] ^ (c >>> 8);
  return (c ^ 0xFFFFFFFF) >>> 0;
}

function bundleZip(templateId, params) {
  const rendered = render(templateId, params);
  const enc = new TextEncoder();
  const entries = [];
  const chunks = [];
  let offset = 0;

  const push = (u8) => { chunks.push(u8); offset += u8.length; };
  const u16 = (v) => new Uint8Array([v & 0xFF, (v >>> 8) & 0xFF]);
  const u32 = (v) => new Uint8Array([v & 0xFF, (v >>> 8) & 0xFF, (v >>> 16) & 0xFF, (v >>> 24) & 0xFF]);

  for (const [path, content] of Object.entries(rendered.files)) {
    const name = enc.encode(`${templateId}/${path}`);
    const data = enc.encode(content);
    const crc = crc32(data);
    const exec = (path === rendered.entry || path === 'run.sh');
    const externalAttr = ((exec ? 0o100755 : 0o100644) << 16) >>> 0;
    const localOffset = offset;

    // local file header
    push(u32(0x04034b50)); push(u16(20)); push(u16(0)); push(u16(0));
    push(u16(0)); push(u16(0));                 // mod time/date (0)
    push(u32(crc)); push(u32(data.length)); push(u32(data.length));
    push(u16(name.length)); push(u16(0));
    push(name); push(data);

    entries.push({ name, crc, size: data.length, localOffset, externalAttr });
  }

  const centralStart = offset;
  for (const e of entries) {
    push(u32(0x02014b50)); push(u16(20)); push(u16(20)); push(u16(0)); push(u16(0));
    push(u16(0)); push(u16(0));                 // mod time/date
    push(u32(e.crc)); push(u32(e.size)); push(u32(e.size));
    push(u16(e.name.length)); push(u16(0)); push(u16(0));
    push(u16(0)); push(u16(0));                 // disk#, internal attr
    push(u32(e.externalAttr)); push(u32(e.localOffset));
    push(e.name);
  }
  const centralSize = offset - centralStart;

  // end of central directory
  push(u32(0x06054b50)); push(u16(0)); push(u16(0));
  push(u16(entries.length)); push(u16(entries.length));
  push(u32(centralSize)); push(u32(centralStart)); push(u16(0));

  const out = new Uint8Array(offset);
  let p = 0;
  for (const c of chunks) { out.set(c, p); p += c.length; }
  return out;
}

function bytesToBase64(bytes) {
  // Runtime-agnostic: no Buffer, no btoa dependency.
  const tbl = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  let out = '';
  for (let i = 0; i < bytes.length; i += 3) {
    const b0 = bytes[i], b1 = bytes[i + 1], b2 = bytes[i + 2];
    out += tbl[b0 >> 2];
    out += tbl[((b0 & 3) << 4) | ((b1 || 0) >> 4)];
    out += i + 1 < bytes.length ? tbl[((b1 & 15) << 2) | ((b2 || 0) >> 6)] : '=';
    out += i + 2 < bytes.length ? tbl[b2 & 63] : '=';
  }
  return out;
}

module.exports = { listTemplates, categories, render, bundleZip, bytesToBase64 };
