#!/usr/bin/env python3
"""
gen_foundry_bundle.py — freeze the Python Worker Foundry (manifest + every
template file) into a single JS module the JS transports can consume.

Cloudflare Pages Functions and the browser can't read arbitrary files, and we
don't want to hand-maintain the 40 templates in two languages. So the Python
templates remain the single source of truth and this script inlines them into
`foundry_bundle.js` (checked in), which `foundry.js` reads. Re-run whenever a
template or the manifest changes:

    python3 apps/aether-console/functions/api/gen_foundry_bundle.py
"""
import json
import os

_HERE = os.path.dirname(os.path.abspath(__file__))
_FOUNDRY = os.path.normpath(os.path.join(
    _HERE, "..", "..", "..", "..", "aether_platform", "foundry"))
_OUT = os.path.join(_HERE, "foundry_bundle.js")


def main() -> None:
    with open(os.path.join(_FOUNDRY, "manifest.json")) as f:
        manifest = json.load(f)

    files = {}  # "<template_id>/<relpath>" -> content
    tdir = os.path.join(_FOUNDRY, "templates")
    for t in manifest["templates"]:
        base = os.path.join(tdir, t["id"])
        for dirpath, _, names in os.walk(base):
            for n in names:
                fp = os.path.join(dirpath, n)
                rel = os.path.relpath(fp, base).replace(os.sep, "/")
                with open(fp, "r", encoding="utf-8") as fh:
                    files[f"{t['id']}/{rel}"] = fh.read()

    bundle = {"manifest": manifest, "files": files}
    payload = json.dumps(bundle, ensure_ascii=False, sort_keys=True, indent=0)

    header = (
        "// AUTO-GENERATED by gen_foundry_bundle.py — do not edit by hand.\n"
        "// Source of truth: aether_platform/foundry/{manifest.json,templates/*}.\n"
        "// Regenerate: python3 apps/aether-console/functions/api/gen_foundry_bundle.py\n"
        "'use strict';\n"
        "const FOUNDRY_BUNDLE = "
    )
    with open(_OUT, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(payload)
        f.write(";\n\nmodule.exports = FOUNDRY_BUNDLE;\n")

    total_bytes = sum(len(v) for v in files.values())
    print(f"wrote {_OUT}: {len(manifest['templates'])} templates, "
          f"{len(files)} files, {total_bytes} template bytes")


if __name__ == "__main__":
    main()
