#!/usr/bin/env python3
"""
LLM Relay (Claude) — reads a JSONL of prompts and calls Claude for each with
bounded concurrency + retry, writing completions as JSONL. Generated by the
Aether Worker Foundry. Uses only stdlib (raw Messages API over HTTPS), so no
`anthropic` package needed.

Input line: {"prompt": "...", "id": "optional"}
Requires:   ANTHROPIC_API_KEY in the environment.
"""
from __future__ import annotations
import argparse, json, os, sys, time
from concurrent.futures import ThreadPoolExecutor
import urllib.request

API = "https://api.anthropic.com/v1/messages"


def call(prompt, model, system, max_tokens, retries):
    key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not key:
        return {"error": "ANTHROPIC_API_KEY not set"}
    payload = {"model": model, "max_tokens": max_tokens, "system": system,
               "messages": [{"role": "user", "content": prompt}]}
    body = json.dumps(payload).encode()
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(API, data=body, method="POST", headers={
                "content-type": "application/json",
                "x-api-key": key,
                "anthropic-version": "2023-06-01",
            })
            with urllib.request.urlopen(req, timeout=120) as r:
                data = json.loads(r.read())
            text = "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")
            return {"text": text, "usage": data.get("usage")}
        except Exception as e:
            if attempt == retries:
                return {"error": str(e)}
            time.sleep(min(30.0, 1.0 * (2 ** attempt)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="{{INPUT}}")
    ap.add_argument("--model", default="{{MODEL}}")
    ap.add_argument("--system", default="{{SYSTEM}}")
    ap.add_argument("--max-tokens", type=int, default=1024)
    ap.add_argument("--concurrency", type=int, default=4)
    ap.add_argument("--retries", type=int, default=3)
    a = ap.parse_args()

    rows = []
    src = sys.stdin if a.input == "-" else open(a.input)
    for line in src:
        line = line.strip()
        if line:
            rows.append(json.loads(line))

    def work(row):
        res = call(row.get("prompt", ""), a.model, a.system, a.max_tokens, a.retries)
        res["id"] = row.get("id")
        return res

    with ThreadPoolExecutor(max_workers=a.concurrency) as pool:
        for res in pool.map(work, rows):
            print(json.dumps(res)); sys.stdout.flush()


if __name__ == "__main__":
    main()
