#!/usr/bin/env python3
"""
Classification Relay (Claude) — reads a JSONL of texts and asks Claude to pick
exactly one label from a fixed set for each, with bounded concurrency + retry.
Generated by the Aether Worker Foundry. Stdlib only (raw Messages API over
HTTPS), so no `anthropic` package needed.

Input line: {"text": "...", "id": "optional"}
Requires:   ANTHROPIC_API_KEY in the environment.
"""
from __future__ import annotations
import argparse, json, os, re, sys, time
from concurrent.futures import ThreadPoolExecutor
import urllib.request

API = "https://api.anthropic.com/v1/messages"


def classify(text, labels, model, retries):
    key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not key:
        return {"error": "ANTHROPIC_API_KEY not set"}
    system = (
        "You are a strict text classifier. Given a piece of text, respond with "
        f"exactly one of these labels, and nothing else: {', '.join(labels)}."
    )
    payload = {"model": model, "max_tokens": 20, "system": system,
               "messages": [{"role": "user", "content": text}]}
    body = json.dumps(payload).encode()
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(API, data=body, method="POST", headers={
                "content-type": "application/json",
                "x-api-key": key,
                "anthropic-version": "2023-06-01",
            })
            with urllib.request.urlopen(req, timeout=60) as r:
                data = json.loads(r.read())
            raw = "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text").strip()
            label = raw if raw in labels else min(labels, key=lambda l: 0 if l.lower() in raw.lower() else 1)
            return {"label": label, "raw": raw}
        except Exception as e:
            if attempt == retries:
                return {"error": str(e)}
            time.sleep(min(30.0, 1.0 * (2 ** attempt)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="{{INPUT}}")
    ap.add_argument("--labels", default="{{LABELS}}")
    ap.add_argument("--model", default="{{MODEL}}")
    ap.add_argument("--concurrency", type=int, default=4)
    ap.add_argument("--retries", type=int, default=3)
    a = ap.parse_args()
    labels = [l.strip() for l in a.labels.split(",") if l.strip()]

    src = sys.stdin if a.input == "-" else open(a.input)
    rows = [json.loads(l) for l in src if l.strip()]

    def work(row):
        res = classify(row.get("text", ""), labels, a.model, a.retries)
        res["id"] = row.get("id")
        return res

    with ThreadPoolExecutor(max_workers=a.concurrency) as pool:
        for res in pool.map(work, rows):
            print(json.dumps(res)); sys.stdout.flush()


if __name__ == "__main__":
    main()
