#!/usr/bin/env python3
"""
Summarization Worker (Claude) — reads every text/markdown file in a directory
and asks Claude to summarize each to a target length, writing one JSONL record
per file. Generated by the Aether Worker Foundry. Stdlib only (raw Messages
API over HTTPS), so no `anthropic` package needed.

Requires: ANTHROPIC_API_KEY in the environment.
"""
from __future__ import annotations
import argparse, glob, json, os, sys, time
from concurrent.futures import ThreadPoolExecutor
import urllib.request

API = "https://api.anthropic.com/v1/messages"


def summarize(text, words, model, retries):
    key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not key:
        return {"error": "ANTHROPIC_API_KEY not set"}
    system = f"Summarize the given document in about {words} words. Be faithful; no preamble."
    payload = {"model": model, "max_tokens": max(256, words * 3), "system": system,
               "messages": [{"role": "user", "content": text[:60000]}]}
    body = json.dumps(payload).encode()
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(API, data=body, method="POST", headers={
                "content-type": "application/json",
                "x-api-key": key,
                "anthropic-version": "2023-06-01",
            })
            with urllib.request.urlopen(req, timeout=120) as r:
                data = json.loads(r.read())
            text_out = "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")
            return {"summary": text_out}
        except Exception as e:
            if attempt == retries:
                return {"error": str(e)}
            time.sleep(min(30.0, 1.0 * (2 ** attempt)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="{{DIR}}")
    ap.add_argument("--glob", default="{{GLOB}}")
    ap.add_argument("--words", type=int, default={{WORDS}})
    ap.add_argument("--model", default="{{MODEL}}")
    ap.add_argument("--concurrency", type=int, default=4)
    ap.add_argument("--retries", type=int, default=3)
    a = ap.parse_args()

    files = sorted(glob.glob(os.path.join(a.dir, a.glob)))

    def work(path):
        try:
            with open(path, encoding="utf-8", errors="replace") as f:
                text = f.read()
        except Exception as e:
            return {"file": path, "error": str(e)}
        res = summarize(text, a.words, a.model, a.retries)
        res["file"] = path
        return res

    with ThreadPoolExecutor(max_workers=a.concurrency) as pool:
        for res in pool.map(work, files):
            print(json.dumps(res)); sys.stdout.flush()

    if not files:
        print(json.dumps({"warning": f"no files matched {a.glob} in {a.dir}"}), file=sys.stderr)


if __name__ == "__main__":
    main()
