"""
Worker Foundry — turn a template + a few params into a real, downloadable
worker. The whole point: spinning up a headless worker should be one pick and
one download, not an afternoon of boilerplate.

`manifest.json` is the source of truth (40 templates). `templates/<id>/` holds
the real, runnable files with `{{TOKEN}}` placeholders. This engine loads them,
substitutes params, and emits either a dict of files or a ready-to-run zip
(worker file + README + run script).

Pure stdlib. A JS mirror (foundry.js, via a checked-in bundle) does the same in
the browser/desktop console so generation works on every transport.
"""
from __future__ import annotations

import io
import json
import os
import re
import stat
import zipfile
from typing import Any, Dict, List, Optional

_HERE = os.path.dirname(os.path.abspath(__file__))
_MANIFEST = os.path.join(_HERE, "manifest.json")
_TEMPLATES = os.path.join(_HERE, "templates")

_TOKEN = re.compile(r"\{\{([A-Z0-9_]+)\}\}")


class FoundryError(ValueError):
    pass


class Foundry:
    def __init__(self, manifest_path: str = _MANIFEST, templates_dir: str = _TEMPLATES):
        with open(manifest_path) as f:
            self.manifest = json.load(f)
        self.templates_dir = templates_dir
        self._by_id = {t["id"]: t for t in self.manifest["templates"]}

    # ── catalog ─────────────────────────────────────────────────────────
    def list_templates(self) -> List[dict]:
        """Metadata only — safe to expose to a UI (no file bodies)."""
        return [
            {
                "id": t["id"], "name": t["name"], "category": t["category"],
                "runtime": t["runtime"], "summary": t["summary"],
                "params": t.get("params", []), "needs": t.get("needs", []),
                "run": t.get("run", ""), "entry": t["entry"],
            }
            for t in self.manifest["templates"]
        ]

    def categories(self) -> List[str]:
        return list(self.manifest.get("categories", []))

    def get(self, template_id: str) -> dict:
        t = self._by_id.get(template_id)
        if not t:
            raise FoundryError(f"unknown template: {template_id}")
        return t

    # ── rendering ───────────────────────────────────────────────────────
    def _resolve_params(self, t: dict, params: Optional[dict]) -> Dict[str, str]:
        params = params or {}
        resolved = {}
        for spec in t.get("params", []):
            name = spec["name"]
            val = params.get(name, spec.get("default", ""))
            resolved[name] = "" if val is None else str(val)
        return resolved

    def _template_files(self, t: dict) -> Dict[str, str]:
        """Read all raw files under templates/<id>/ as {relpath: text}."""
        base = os.path.join(self.templates_dir, t["id"])
        if not os.path.isdir(base):
            raise FoundryError(f"template files missing on disk: {t['id']}")
        files = {}
        for dirpath, _, names in os.walk(base):
            for n in names:
                fp = os.path.join(dirpath, n)
                rel = os.path.relpath(fp, base)
                with open(fp, "r", encoding="utf-8") as fh:
                    files[rel] = fh.read()
        return files

    def _substitute(self, text: str, params: Dict[str, str]) -> str:
        def repl(m):
            key = m.group(1)
            if key not in params:
                return m.group(0)  # leave unknown tokens intact
            return params[key]
        return _TOKEN.sub(repl, text)

    def render(self, template_id: str, params: Optional[dict] = None) -> dict:
        """
        Return {template_id, entry, runtime, run, files:{path:content}}.
        `files` includes the substituted worker file(s) plus a generated
        README.md and a run.sh — everything needed to run it.
        """
        t = self.get(template_id)
        resolved = self._resolve_params(t, params)
        raw = self._template_files(t)
        files = {path: self._substitute(body, resolved) for path, body in raw.items()}
        files["README.md"] = self._readme(t, resolved)
        files["run.sh"] = self._runscript(t)
        return {
            "template_id": t["id"], "name": t["name"], "entry": t["entry"],
            "runtime": t["runtime"], "run": t.get("run", ""),
            "params": resolved, "files": files,
        }

    def _readme(self, t: dict, params: Dict[str, str]) -> str:
        lines = [
            f"# {t['name']}", "",
            t["summary"], "",
            f"- **Category:** {t['category']}",
            f"- **Runtime:** {t['runtime']}",
            f"- **Generated by:** Aether Worker Foundry", "",
            "## Run", "", "```bash", t.get("run", ""), "```", "",
        ]
        if params:
            lines += ["## Baked-in parameters", "",
                      "These are the defaults compiled into the file; every one is also a "
                      "CLI flag (`--lower-kebab-name`) you can override at run time.", ""]
            for k, v in params.items():
                lines.append(f"- `{k}` = `{v or '(empty)'}`")
            lines.append("")
        needs = t.get("needs", [])
        if needs:
            lines += ["## Requirements", ""] + [f"- {n}" for n in needs] + [""]
        lines += ["---", "",
                  "Regenerate or customize this worker any time from the Aether console "
                  "(Foundry tab) or by asking Claude in the Worker Studio."]
        return "\n".join(lines)

    def _runscript(self, t: dict) -> str:
        rt = t["runtime"]
        pre = "#!/usr/bin/env bash\nset -euo pipefail\ncd \"$(dirname \"$0\")\"\n\n"
        if rt == "node":
            pre += "command -v node >/dev/null || { echo 'Node.js required'; exit 1; }\n"
            pre += "[ -d node_modules ] || npm i playwright\n"
        else:
            pre += "command -v python3 >/dev/null || { echo 'python3 required'; exit 1; }\n"
        return pre + t.get("run", "") + "\n"

    def bundle_zip(self, template_id: str, params: Optional[dict] = None) -> bytes:
        """Render and pack into a zip (worker file(s) + README + run.sh)."""
        rendered = self.render(template_id, params)
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
            for path, content in rendered["files"].items():
                info = zipfile.ZipInfo(f"{template_id}/{path}")
                # make the entry + run.sh executable
                info.external_attr = (stat.S_IFREG | 0o755) << 16 if path in (rendered["entry"], "run.sh") \
                    else (stat.S_IFREG | 0o644) << 16
                z.writestr(info, content)
        return buf.getvalue()


# module-level singleton for convenience
_default: Optional[Foundry] = None


def default() -> Foundry:
    global _default
    if _default is None:
        _default = Foundry()
    return _default
