#!/usr/bin/env python3
"""
ETL Normalizer — reads CSV or JSON, applies a field map + light type coercion,
and writes normalized JSONL. Generated by the Aether Worker Foundry. Stdlib
only. Edit FIELD_MAP and COERCE for your schema.
"""
from __future__ import annotations
import argparse, csv, json, sys

# output_field -> input_field  (rename/select). Empty = pass everything through.
FIELD_MAP = {}
# output_field -> "int" | "float" | "bool" | "str"
COERCE = {}


def coerce(val, kind):
    try:
        if kind == "int": return int(float(val))
        if kind == "float": return float(val)
        if kind == "bool": return str(val).strip().lower() in ("1", "true", "yes", "y", "t")
        return "" if val is None else str(val)
    except (ValueError, TypeError):
        return None


def normalize(row: dict) -> dict:
    out = {}
    if FIELD_MAP:
        for out_f, in_f in FIELD_MAP.items():
            out[out_f] = row.get(in_f)
    else:
        out = dict(row)
    for f, kind in COERCE.items():
        if f in out:
            out[f] = coerce(out[f], kind)
    return out


def read_rows(path):
    if path.endswith(".json"):
        data = json.load(open(path))
        yield from (data if isinstance(data, list) else [data])
    else:
        with open(path, newline="") as f:
            yield from csv.DictReader(f)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="{{INPUT}}")
    ap.add_argument("--output", default="{{OUTPUT}}")
    a = ap.parse_args()
    n = 0
    out = sys.stdout if a.output == "-" else open(a.output, "w")
    for row in read_rows(a.input):
        out.write(json.dumps(normalize(row)) + "\n"); n += 1
    if out is not sys.stdout:
        out.close()
    print(json.dumps({"done": True, "rows": n, "output": a.output}), file=sys.stderr)


if __name__ == "__main__":
    main()
