#!/usr/bin/env python3
"""
Work Queue Consumer — generic claim -> process -> ack/nack loop against any HTTP
queue that exposes POST /claim, /ack, /nack. Drop your logic into handle().
Generated by the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, sys, time
import urllib.request


def _post(base, path, payload, timeout=20):
    req = urllib.request.Request(base.rstrip("/") + path, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read() or b"{}")


def handle(item: dict) -> dict:
    """Edit me. Receives a claimed item, returns a result dict (stored on ack)."""
    return {"processed": True, "echo": item}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--queue", default="{{QUEUE}}")
    ap.add_argument("--name", default="{{NAME}}")
    ap.add_argument("--idle", type=float, default=1.0)
    a = ap.parse_args()
    done = 0
    print(f"[queue-consumer {a.name}] draining {a.queue}", file=sys.stderr)
    while True:
        try:
            item = _post(a.queue, "/claim", {"consumer": a.name})
        except Exception:
            time.sleep(a.idle); continue
        if not item or item.get("empty"):
            time.sleep(a.idle); continue
        try:
            result = handle(item)
            _post(a.queue, "/ack", {"consumer": a.name, "id": item.get("id"), "result": result})
            done += 1
            if done % 20 == 0:
                print(json.dumps({"acked": done}), file=sys.stderr)
        except Exception as e:
            try: _post(a.queue, "/nack", {"consumer": a.name, "id": item.get("id"), "error": str(e)})
            except Exception: pass


if __name__ == "__main__":
    main()
