#!/usr/bin/env python3
"""
Log Shipper — tails a growing log file (survives truncation/rotation via inode
+ size tracking) and ships new lines to an HTTP sink in batches. Generated by
the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, os, sys, time
import urllib.request


def ship(sink, lines):
    req = urllib.request.Request(sink, data=json.dumps({"lines": lines}).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", default="{{FILE}}")
    ap.add_argument("--sink", default="{{SINK}}")
    ap.add_argument("--batch", type=int, default=200)
    ap.add_argument("--flush-secs", type=float, default=2.0)
    a = ap.parse_args()

    pos, inode = 0, None
    buf, last_flush = [], time.time()
    while True:
        try:
            st = os.stat(a.file)
        except FileNotFoundError:
            time.sleep(1.0); continue
        if inode != st.st_ino or st.st_size < pos:   # rotated or truncated
            pos, inode = 0, st.st_ino
        if st.st_size > pos:
            with open(a.file, "r", errors="replace") as f:
                f.seek(pos)
                for line in f:
                    if line.endswith("\n"):
                        buf.append(line.rstrip("\n"))
                    else:
                        break  # partial line; wait for the rest
                pos = f.tell()
        now = time.time()
        if buf and (len(buf) >= a.batch or now - last_flush >= a.flush_secs):
            chunk, buf = buf[:a.batch], buf[a.batch:]
            try:
                ship(a.sink, chunk)
                print(json.dumps({"shipped": len(chunk)}), file=sys.stderr)
            except Exception as e:
                buf = chunk + buf  # requeue on failure
                print(json.dumps({"ship_error": str(e)}), file=sys.stderr)
            last_flush = now
        time.sleep(0.3)


if __name__ == "__main__":
    main()
