#!/usr/bin/env python3
"""
Cron Runner — runs a shell command on a fixed interval (with a little jitter),
captures output, and POSTs to a webhook on non-zero exit. Generated by the
Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, random, subprocess, sys, time
import urllib.request


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--command", default="{{COMMAND}}")
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--webhook", default="{{WEBHOOK}}")
    ap.add_argument("--jitter", type=float, default=0.1, help="fraction of interval")
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()

    while True:
        t0 = time.time()
        try:
            p = subprocess.run(a.command, shell=True, capture_output=True, text=True, timeout=a.interval)
            rec = {"command": a.command, "returncode": p.returncode,
                   "duration_s": round(time.time() - t0, 3),
                   "stdout": p.stdout[-4000:], "stderr": p.stderr[-4000:], "ts": time.time()}
        except subprocess.TimeoutExpired:
            rec = {"command": a.command, "returncode": None, "error": "timeout", "ts": time.time()}
        print(json.dumps({k: rec[k] for k in ("command", "returncode", "duration_s") if k in rec}))
        sys.stdout.flush()
        if a.webhook and rec.get("returncode") not in (0,):
            try: post(a.webhook, rec)
            except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
        if a.once:
            break
        time.sleep(max(1, a.interval + random.uniform(-a.jitter, a.jitter) * a.interval))


if __name__ == "__main__":
    main()
