#!/usr/bin/env python3
"""
Webhook Relay / Transformer — receives webhooks on POST /, applies a small
transform (edit `transform()`), and forwards to one or more destinations with
retry. Generated by the Aether Worker Foundry. Stdlib HTTP server.
"""
from __future__ import annotations
import argparse, json, threading, time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
import urllib.request

FORWARD_TO = [u.strip() for u in "{{FORWARD_TO}}".split(",") if u.strip()]


def transform(event: dict) -> dict:
    """Edit me. Receives the incoming JSON, returns what gets forwarded."""
    event["_relayed_at"] = time.time()
    return event


def forward(payload):
    for dest in FORWARD_TO:
        for attempt in range(3):
            try:
                req = urllib.request.Request(dest, data=json.dumps(payload).encode(),
                                             headers={"Content-Type": "application/json"}, method="POST")
                urllib.request.urlopen(req, timeout=15).read()
                break
            except Exception:
                time.sleep(0.5 * (2 ** attempt))


class H(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    def log_message(self, *a): pass
    def _send(self, code, data):
        body = json.dumps(data).encode()
        self.send_response(code); self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body))); self.end_headers(); self.wfile.write(body)
    def do_GET(self):
        self._send(200, {"status": "relay-ready", "forward_to": FORWARD_TO})
    def do_POST(self):
        n = int(self.headers.get("Content-Length", 0))
        try:
            event = json.loads(self.rfile.read(n)) if n else {}
        except Exception:
            self._send(400, {"ok": False, "error": "bad_json"}); return
        out = transform(event)
        threading.Thread(target=forward, args=(out,), daemon=True).start()
        self._send(200, {"ok": True, "forwarded_to": len(FORWARD_TO)})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", default="0.0.0.0")
    ap.add_argument("--port", type=int, default={{PORT}})
    a = ap.parse_args()
    print(f"[webhook-relay] http://{a.host}:{a.port} -> {FORWARD_TO or '(no destinations set)'}")
    ThreadingHTTPServer((a.host, a.port), H).serve_forever()


if __name__ == "__main__":
    main()
