#!/usr/bin/env python3
"""
Mesh Compute Node (native, pull) — joins the Aether pull-mesh: dials OUT to a
coordinator (works behind NAT), claims Kuramoto chunks, computes them, and
submits results. Uses the compiled native C++ engine if it's importable, else a
self-contained pure-Python kernel (same global-index seeding, so results stitch
consistently). Generated by the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, math, os, sys, time
import urllib.request

_MASK = (1 << 64) - 1


# ── pure-Python fallback kernel (used if the native engine isn't importable) ──
def _sm64(s):
    s = (s + 0x9E3779B97F4A7C15) & _MASK
    z = s
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & _MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & _MASK
    return (z ^ (z >> 31)), s


def _r01(s):
    z, s = _sm64(s)
    return (z >> 11) * (1.0 / (1 << 53)), s


def _sim_one(nodes, steps, coupling, dt, seed):
    s = (seed + 1) & _MASK
    ph, fr = [], []
    for _ in range(nodes):
        u, s = _r01(s); ph.append(2 * math.pi * u)
    for _ in range(nodes):
        u, s = _r01(s); fr.append(u - 0.5)
    for _ in range(steps):
        sx = sum(math.cos(p) for p in ph); sy = sum(math.sin(p) for p in ph)
        psi = math.atan2(sy, sx); r = math.hypot(sx, sy) / nodes
        for i in range(nodes):
            ph[i] = math.fmod(ph[i] + dt * (fr[i] + coupling * r * math.sin(psi - ph[i])), 2 * math.pi)
    sx = sum(math.cos(p) for p in ph); sy = sum(math.sin(p) for p in ph)
    return math.hypot(sx, sy) / nodes


def _load_native():
    """Return a callable(begin,end,nodes,steps,coupling,dt,seed)->list, or None."""
    here = os.path.dirname(os.path.abspath(__file__))
    for cand in (os.path.join(here, "..", "..", "..", "organism", "cpp", "bindings", "python"),
                 os.path.join(here, "organism", "cpp", "bindings", "python")):
        cand = os.path.normpath(cand)
        if os.path.isdir(cand) and cand not in sys.path:
            sys.path.insert(0, cand)
    try:
        from organism_native import NativeEngine  # noqa
        eng = NativeEngine()
        def run(begin, end, nodes, steps, coupling, dt, seed):
            # native seeds by LOCAL index, so a global range uses seed+begin
            return eng.batch_simulate(population_count=end - begin, nodes_per_population=nodes,
                                      steps=steps, coupling=coupling, dt=dt, seed=seed + begin, threads=-1)
        return run, "native"
    except Exception:
        def run(begin, end, nodes, steps, coupling, dt, seed):
            return [_sim_one(nodes, steps, coupling, dt, seed + p) for p in range(begin, end)]
        return run, "python"


def _post(base, path, payload, timeout=30):
    req = urllib.request.Request(base.rstrip("/") + path, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read() or b"{}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--server", default="{{SERVER}}")
    ap.add_argument("--name", default="{{NAME}}")
    ap.add_argument("--idle", type=float, default=0.6)
    a = ap.parse_args()

    run, backend = _load_native()
    print(f"[mesh-native-worker {a.name}] joining {a.server} (kernel: {backend})", file=sys.stderr)
    computed = 0
    while True:
        try:
            chunk = _post(a.server, "/mesh/claim", {"node_id": a.name})
        except Exception:
            time.sleep(a.idle); continue
        if not chunk or chunk.get("empty"):
            time.sleep(a.idle); continue
        try:
            coh = run(int(chunk["range_begin"]), int(chunk["range_end"]), int(chunk["nodes"]),
                      int(chunk["steps"]), float(chunk["coupling"]), float(chunk["dt"]), int(chunk["seed"]))
            _post(a.server, "/mesh/submit", {"job_id": chunk["job_id"], "chunk_id": chunk["chunk_id"],
                                             "node_id": a.name, "coherences": coh})
            computed += len(coh)
            if computed % 500 < len(coh):
                print(json.dumps({"computed": computed, "kernel": backend}), file=sys.stderr)
        except Exception as e:
            print(json.dumps({"error": str(e)}), file=sys.stderr)


if __name__ == "__main__":
    main()
