import * as THREE from 'three';
import { VRButton } from 'three/addons/webxr/VRButton.js';
import { XRControllerModelFactory } from 'three/addons/webxr/XRControllerModelFactory.js';
import { Sky } from 'three/addons/objects/Sky.js';
import { Water } from 'three/addons/objects/Water.js';

const W={pond:24,shore:48,fish:44};
const BAITS=[
{name:'Nightcrawler',a:1,s:.16,c:0x8d4e38},{name:'Silver Minnow',a:1.22,s:.28,c:0xc8dde8},
{name:'Stink Bait',a:1.42,s:.42,c:0x8b7452},{name:'Golden Dough',a:1.72,s:.12,c:0xffc84a},
{name:'Topwater Frog',a:1.36,s:.02,c:0x4eaa58}
];
const WEATHER=[
{name:'Clear Dawn',fog:0x92bdc6,water:0x176b7c,wind:.12,bite:1.05,light:1},
{name:'Cloud Break',fog:0x80959d,water:0x315d68,wind:.32,bite:1.15,light:.72},
{name:'Golden Evening',fog:0xb69172,water:0x355f66,wind:.18,bite:1.25,light:.86},
{name:'Night Glass',fog:0x14283a,water:0x0a3444,wind:.08,bite:1.4,light:.3}
];
const SPECIES=[
{name:'Bluegill',c:0x5d9db4,b:0xbad9df,min:.25,max:1.5,v:8,p:.52,r:.34,d:[.35,1.2],bait:[1,1,.55,.7,.65],school:5},
{name:'Crappie',c:0xaebcb2,b:0xdce3d8,min:.5,max:2.4,v:14,p:.72,r:.23,d:[.6,1.8],bait:[1,.95,.65,.6,.5],school:4},
{name:'Largemouth Bass',c:0x658453,b:0xc8d1a7,min:1.2,max:9.5,v:32,p:1.25,r:.18,d:[.8,2.7],bait:[.6,1.35,.45,.8,1.65],school:1},
{name:'Channel Catfish',c:0x707986,b:0xa7adb4,min:2.5,max:22,v:48,p:1.62,r:.11,d:[1.2,3.8],bait:[.7,.7,1.6,.55,.12],school:1},
{name:'Golden Koi',c:0xf6a629,b:0xffe5a5,min:1.5,max:8.5,v:120,p:1.4,r:.055,d:[.45,1.7],bait:[.45,.55,.35,1.7,.2],school:2},
{name:"Bryan's Legend",c:0x37d8c0,b:0xc6fff3,min:14,max:31,v:400,p:2.35,r:.015,d:[1.8,4.2],bait:[.15,.65,1.1,2,.55],school:1}
];
const MISSIONS=[
{id:'species',text:'Catch 3 different species',reward:180},{id:'heavy',text:'Land a fish over 8 lb',reward:240},
{id:'clean',text:'Land without redlining tension',reward:160},{id:'night',text:'Catch during Night Glass',reward:220}
];
const get=(k,f)=>{try{const v=localStorage.getItem(k);return v==null?f:JSON.parse(v)}catch{return f}};
const st={coins:get('bp3-coins',0),xp:get('bp3-xp',0),best:get('bp3-best',null),catches:get('bp3-catches',[]),bait:get('bp3-bait',0),rod:get('bp3-rod',1),line:get('bp3-line',1),reel:get('bp3-reel',1),drag:get('bp3-drag',.55),weather:get('bp3-weather',0),mission:get('bp3-mission',null),phase:'idle',tension:0,reeling:0,fish:null,castV:new THREE.Vector3(),time:0,bite:0,cool:0,wear:0,maxT:0,lastSnap:0,lastAngle:null,species:new Set()};
if(!st.mission)st.mission={...MISSIONS[Math.floor(Math.random()*MISSIONS.length)],complete:false,progress:0};
const save=()=>{for(const [k,v] of Object.entries({coins:st.coins,xp:st.xp,best:st.best,catches:st.catches.slice(-80),bait:st.bait,rod:st.rod,line:st.line,reel:st.reel,drag:st.drag,weather:st.weather,mission:st.mission}))localStorage.setItem('bp3-'+k,JSON.stringify(v))};
const q=s=>document.querySelector(s),msg=(t,n=2)=>{q('#status').textContent=t;q('#status').classList.add('show');st.msg=n};
let scene,camera,renderer,clock,player,water,sky,sun,rod,tip,reel,bobber,line,lure,net,wrist,wc,wt,ctlL,ctlR,gripL,gripR,vignette;
const fish=[],ripples=[],drops=[],birds=[],bugs=[],reeds=[],tmp=new THREE.Vector3(),tmp2=new THREE.Vector3(),quat=new THREE.Quaternion();
const haptic=(s=.45,d=45,left=false)=>{const gp=(left?ctlL:ctlR)?.userData?.gamepad,a=gp?.hapticActuators?.[0]||gp?.vibrationActuator;try{a?.pulse?.(s,d)}catch{}};
const tone=(f=420,d=.08,v=.05)=>{try{const c=tone.c||(tone.c=new AudioContext()),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(v,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+d)}catch{}};
const wx=()=>WEATHER[st.weather%WEATHER.length];
function hud(){q('#score').textContent=`Coins ${st.coins} • XP ${st.xp}`;q('#record').textContent=st.best?`Best: ${st.best.name} ${st.best.weight.toFixed(1)} lb`:'Best: none';q('#weather').textContent=`${wx().name} • ${BAITS[st.bait].name}`;q('#gear').textContent=`Rod ${st.rod} • Line ${st.line} • Reel ${st.reel} • Drag ${Math.round(st.drag*100)}%`;q('#mission').textContent=`Mission: ${st.mission.text}${st.mission.complete?' ✓':''}`;drawWrist()}
function init(){scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x91b8bd,.012);camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.04,260);camera.position.set(0,1.68,29);player=new THREE.Group();player.add(camera);scene.add(player);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.35));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');document.body.appendChild(renderer.domElement);document.body.appendChild(VRButton.createButton(renderer,{requiredFeatures:['local-floor'],optionalFeatures:['bounded-floor','hand-tracking','layers']}));clock=new THREE.Clock();world();controllers();desktop();hud();renderer.setAnimationLoop(loop);addEventListener('resize',resize);q('#loading').style.display='none'}
function world(){scene.add(new THREE.HemisphereLight(0xd8f4ff,0x273d2b,1.45));sun=new THREE.DirectionalLight(0xffefcf,3.1);sun.position.set(-18,28,12);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-42;sun.shadow.camera.right=42;sun.shadow.camera.top=42;sun.shadow.camera.bottom=-42;scene.add(sun);sky=new Sky();sky.scale.setScalar(360);scene.add(sky);Object.assign(sky.material.uniforms,{ });sky.material.uniforms.turbidity.value=7;sky.material.uniforms.rayleigh.value=2.1;sky.material.uniforms.mieCoefficient.value=.008;sky.material.uniforms.mieDirectionalG.value=.84;terrain();pond();dock();nature();gear();comfort();for(let i=0;i<W.fish;i++)spawn(i)}
function terrain(){const g=new THREE.CircleGeometry(W.shore,144),p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getY(i),r=Math.hypot(x,z),n=Math.sin(x*.31)*.22+Math.cos(z*.27)*.18+Math.sin((x+z)*.13)*.12;p.setZ(i,Math.max(0,(r-W.pond)*.04)+n*(r/W.shore))}g.computeVertexNormals();const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x466e3b,roughness:1}));m.rotation.x=-Math.PI/2;m.receiveShadow=true;scene.add(m);const beach=new THREE.Mesh(new THREE.RingGeometry(W.pond-1.5,W.pond+3.2,144),new THREE.MeshStandardMaterial({color:0xb39568,roughness:1}));beach.rotation.x=-Math.PI/2;beach.position.y=.025;scene.add(beach)}
function pond(){const n=new THREE.TextureLoader().load('https://threejs.org/examples/textures/waternormals.jpg',t=>{t.wrapS=t.wrapT=THREE.RepeatWrapping});water=new Water(new THREE.CircleGeometry(W.pond,144),{textureWidth:512,textureHeight:512,waterNormals:n,sunDirection:new THREE.Vector3(),sunColor:0xffffff,waterColor:wx().water,distortionScale:2.5,fog:true});water.rotation.x=-Math.PI/2;water.position.y=.06;scene.add(water);const bottom=new THREE.Mesh(new THREE.CircleGeometry(W.pond-.4,120),new THREE.MeshStandardMaterial({color:0x1f382c,roughness:1}));bottom.rotation.x=-Math.PI/2;bottom.position.y=-4.5;scene.add(bottom);for(let i=0;i<28;i++){const pad=new THREE.Mesh(new THREE.CircleGeometry(.18+Math.random()*.28,16),new THREE.MeshStandardMaterial({color:0x3f7c4a,side:THREE.DoubleSide}));const a=Math.random()*Math.PI*2,r=3+Math.random()*(W.pond-4);pad.rotation.x=-Math.PI/2;pad.position.set(Math.cos(a)*r,.075,Math.sin(a)*r);scene.add(pad)}}
function dock(){const wood=new THREE.MeshStandardMaterial({color:0x765238,roughness:.88}),dark=new THREE.MeshStandardMaterial({color:0x3f2a20,roughness:1}),d=new THREE.Group();for(let i=0;i<18;i++){const p=new THREE.Mesh(new THREE.BoxGeometry(1.8,.16,.75),wood);p.position.set(0,.22,17+i*.71);p.castShadow=p.receiveShadow=true;d.add(p)}for(const x of [-.72,.72])for(const z of [17.2,21.5,26.5,29]){const p=new THREE.Mesh(new THREE.CylinderGeometry(.1,.13,3.1,8),dark);p.position.set(x,-.75,z);d.add(p)}scene.add(d);const c=new THREE.Group();c.position.set(-15,0,25);const b=new THREE.Mesh(new THREE.BoxGeometry(7,3.5,5.4),new THREE.MeshStandardMaterial({color:0x68472f,roughness:.94}));b.position.y=1.75;b.castShadow=true;c.add(b);const r=new THREE.Mesh(new THREE.ConeGeometry(5.1,2.4,4),new THREE.MeshStandardMaterial({color:0x302a27}));r.rotation.y=Math.PI/4;r.position.y=4.65;r.scale.z=.8;c.add(r);scene.add(c)}
function nature(){const tr=new THREE.MeshStandardMaterial({color:0x5c3d28}),lf=new THREE.MeshStandardMaterial({color:0x2e6a3b});for(let i=0;i<72;i++){const a=Math.random()*Math.PI*2,r=W.pond+6+Math.random()*(W.shore-W.pond-7),t=new THREE.Group(),x=new THREE.Mesh(new THREE.CylinderGeometry(.18,.28,3.2,8),tr);x.position.y=1.6;t.add(x);for(let j=0;j<3;j++){const c=new THREE.Mesh(new THREE.ConeGeometry(1.45-j*.14,2.6,9),lf);c.position.y=3.4+j*1.1;t.add(c)}t.position.set(Math.cos(a)*r,0,Math.sin(a)*r);t.scale.setScalar(.75+Math.random()*.65);scene.add(t)}const rm=new THREE.MeshStandardMaterial({color:0x547c35});for(let i=0;i<190;i++){const a=Math.random()*Math.PI*2,r=W.pond-1.2+Math.random()*2.7,x=new THREE.Mesh(new THREE.CylinderGeometry(.018,.028,.65+Math.random(),5),rm);x.position.set(Math.cos(a)*r,.35,Math.sin(a)*r);x.userData.p=Math.random()*6.28;scene.add(x);reeds.push(x)}for(let i=0;i<9;i++){const b=new THREE.Group(),m=new THREE.MeshBasicMaterial({color:0x1c2226}),w1=new THREE.Mesh(new THREE.PlaneGeometry(.38,.08),m),w2=w1.clone();w1.rotation.z=.35;w2.rotation.z=-.35;w1.position.x=-.2;w2.position.x=.2;b.add(w1,w2);b.userData={r:22+Math.random()*23,s:.045+Math.random()*.06,p:Math.random()*6.28,h:9+Math.random()*8};scene.add(b);birds.push(b)}for(let i=0;i<52;i++){const b=new THREE.Mesh(new THREE.SphereGeometry(.018,5,4),new THREE.MeshBasicMaterial({color:0xffe98b}));b.userData={c:new THREE.Vector3((Math.random()-.5)*24,1+Math.random()*2.6,(Math.random()-.5)*24),p:Math.random()*6.28};scene.add(b);bugs.push(b)}}
function gear(){rod=new THREE.Group();const cork=new THREE.MeshStandardMaterial({color:0xb98a59}),graph=new THREE.MeshStandardMaterial({color:0x20272b,metalness:.58,roughness:.28}),h=new THREE.Mesh(new THREE.CylinderGeometry(.035,.047,.55,12),cork);h.rotation.z=Math.PI/2;h.position.x=.27;rod.add(h);const s=new THREE.Mesh(new THREE.CylinderGeometry(.007,.018,2.15,12),graph);s.rotation.z=Math.PI/2;s.position.x=1.52;rod.add(s);reel=new THREE.Group();const sp=new THREE.Mesh(new THREE.CylinderGeometry(.095,.095,.09,20),new THREE.MeshStandardMaterial({color:0x59636b,metalness:.82}));sp.rotation.z=Math.PI/2;reel.add(sp);reel.position.set(.47,-.1,0);rod.add(reel);tip=new THREE.Object3D();tip.position.set(2.62,0,0);rod.add(tip);line=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:0xe7fbff,transparent:true,opacity:.9}));scene.add(line);bobber=new THREE.Mesh(new THREE.SphereGeometry(.078,16,12),new THREE.MeshStandardMaterial({color:0xff493d,emissive:0x5b0803}));bobber.visible=false;scene.add(bobber);lure=new THREE.Mesh(new THREE.SphereGeometry(.042,10,8),new THREE.MeshStandardMaterial({color:BAITS[st.bait].c,metalness:.18}));bobber.add(lure);lure.position.y=-.22;camera.add(rod);rod.position.set(.24,-.22,-.52);net=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(.34,.025,8,28),graph);ring.rotation.y=Math.PI/2;net.add(ring);net.position.set(-.55,-.35,-.7);camera.add(net);wc=document.createElement('canvas');wc.width=512;wc.height=256;wt=new THREE.CanvasTexture(wc);wrist=new THREE.Mesh(new THREE.PlaneGeometry(.34,.17),new THREE.MeshBasicMaterial({map:wt,side:THREE.DoubleSide}));wrist.position.set(0,.07,-.11);drawWrist()}
function comfort(){vignette=new THREE.Mesh(new THREE.RingGeometry(.38,.78,64),new THREE.MeshBasicMaterial({color:0,transparent:true,opacity:0,side:THREE.DoubleSide,depthTest:false}));vignette.position.set(0,0,-.45);camera.add(vignette)}
function drawWrist(){if(!wc)return;const c=wc.getContext('2d');c.fillStyle='#07131f';c.fillRect(0,0,512,256);c.strokeStyle='#68efd0';c.lineWidth=5;c.strokeRect(4,4,504,248);c.fillStyle='#68efd0';c.font='bold 30px sans-serif';c.fillText("BRYAN'S POND",22,42);c.fillStyle='white';c.font='24px monospace';c.fillText(BAITS[st.bait].name,22,82);c.fillText(`Drag ${Math.round(st.drag*100)}%`,22,118);c.fillText(`Coins ${st.coins}`,22,154);c.fillText(`XP ${st.xp}`,22,190);c.fillStyle=st.mission.complete?'#62d88f':'#ffcf65';c.font='19px sans-serif';c.fillText(st.mission.text.slice(0,38),22,228);wt.needsUpdate=true}
function model(s,w){const f=new THREE.Group(),sc=.52+Math.min(1.5,w/s.max)*1.02,bm=new THREE.MeshPhysicalMaterial({color:s.c,roughness:.34,clearcoat:.32}),bel=new THREE.MeshStandardMaterial({color:s.b}),body=new THREE.Mesh(new THREE.SphereGeometry(.34,24,14),bm);body.scale.set(1.85,.72,.8);f.add(body);const belly=new THREE.Mesh(new THREE.SphereGeometry(.31,20,12),bel);belly.scale.set(1.58,.5,.7);belly.position.y=-.13;f.add(belly);const piv=new THREE.Group();piv.position.x=-.68;const tail=new THREE.Mesh(new THREE.ConeGeometry(.32,.62,3),bm);tail.rotation.z=-Math.PI/2;tail.position.x=-.18;piv.add(tail);f.add(piv);const fin=new THREE.Mesh(new THREE.ConeGeometry(.16,.38,3),bm);fin.position.set(-.05,.35,0);fin.rotation.z=Math.PI;f.add(fin);for(const z of [-.23,.23]){const e=new THREE.Mesh(new THREE.SphereGeometry(.045,10,8),new THREE.MeshBasicMaterial({color:0xffffff}));e.position.set(.43,.11,z);f.add(e);const p=new THREE.Mesh(new THREE.SphereGeometry(.022,8,6),new THREE.MeshBasicMaterial({color:0}));p.position.set(.47,.11,z*1.08);f.add(p)}f.userData.tail=piv;f.scale.setScalar(sc);return f}
function choose(){let r=Math.random(),sum=0;for(const s of SPECIES){sum+=s.r;if(r<=sum)return s}return SPECIES[0]}
function spawn(i=0){const s=choose(),w=s.min+Math.pow(Math.random(),1.5)*(s.max-s.min),f=model(s,w),a=Math.random()*Math.PI*2,r=3+Math.random()*(W.pond-4),d=s.d[0]+Math.random()*(s.d[1]-s.d[0]);f.position.set(Math.cos(a)*r,-d,Math.sin(a)*r);f.rotation.y=Math.random()*Math.PI*2;Object.assign(f.userData,{s,w,h:f.rotation.y,spd:.28+Math.random()*.52,turn:0,int:0,stam:1,burst:0,wander:Math.random()*10,school:i%7});scene.add(f);fish.push(f)}
function controllers(){const fac=new XRControllerModelFactory();ctlL=renderer.xr.getController(0);ctlR=renderer.xr.getController(1);gripL=renderer.xr.getControllerGrip(0);gripR=renderer.xr.getControllerGrip(1);gripL.add(fac.createControllerModel(gripL));gripR.add(fac.createControllerModel(gripR));player.add(ctlL,ctlR,gripL,gripR);ctlL.addEventListener('connected',e=>ctlL.userData.gamepad=e.data.gamepad);ctlR.addEventListener('connected',e=>ctlR.userData.gamepad=e.data.gamepad);ctlR.addEventListener('selectstart',action);ctlR.addEventListener('squeezestart',()=>st.reeling=1);ctlR.addEventListener('squeezeend',()=>st.reeling=0);ctlL.addEventListener('selectstart',bait);ctlL.addEventListener('squeezestart',()=>drag(.05));gripL.add(wrist)}
function desktop(){addEventListener('pointerdown',e=>{if(e.button===0)action();if(e.button===2)st.reeling=1});addEventListener('pointerup',()=>st.reeling=0);addEventListener('contextmenu',e=>e.preventDefault());addEventListener('keydown',e=>{if(e.code==='KeyB')bait();if(e.code==='KeyR')st.reeling=1;if(e.code==='BracketLeft')drag(-.05);if(e.code==='BracketRight')drag(.05);if(e.code==='KeyW')cycleWeather()});addEventListener('keyup',e=>{if(e.code==='KeyR')st.reeling=0})}
function bait(){st.bait=(st.bait+1)%BAITS.length;lure.material.color.setHex(BAITS[st.bait].c);msg(BAITS[st.bait].name);hud();save()}
function drag(x){st.drag=THREE.MathUtils.clamp(st.drag+x,.2,.9);msg(`Drag ${Math.round(st.drag*100)}%`);hud();save();haptic(.25,30,true)}
function cycleWeather(){st.weather=(st.weather+1)%WEATHER.length;msg(wx().name,2.5);hud();save()}
function action(){if(st.cool>0)return;if(st.phase==='idle')cast();else if(st.phase==='bite')hook();else if(st.phase==='landed'){st.phase='idle';st.fish=null;bobber.visible=false;q('#tension-wrap').classList.remove('show')}}
function origin(){const o=new THREE.Vector3(),d=new THREE.Vector3();if(renderer.xr.isPresenting){tip.getWorldPosition(o);ctlR.getWorldDirection(d);d.multiplyScalar(-1)}else{o.copy(camera.position);camera.getWorldDirection(d)}return{o,d}}
function cast(){const {o,d}=origin();st.phase='casting';st.cool=.45;st.maxT=0;bobber.position.copy(o);bobber.visible=true;st.castV.copy(d).multiplyScalar(10.8+st.rod*1.25);st.castV.y=Math.max(4.5,st.castV.y+5.8);msg('Cast');haptic(.3,35)}
function hook(){if(!st.fish)return;st.phase='fight';st.tension=.38;st.fish.userData.stam=1;st.fish.userData.burst=.5;q('#tension-wrap').classList.add('show');msg(`Hooked ${st.fish.userData.s.name}!`);haptic(.85,110);tone(720,.12,.07)}
function ripple(p){const r=new THREE.Mesh(new THREE.RingGeometry(.06,.1,32),new THREE.MeshBasicMaterial({color:0xbff7ff,transparent:true,opacity:.75,side:THREE.DoubleSide}));r.rotation.x=-Math.PI/2;r.position.copy(p);r.position.y=.07;r.userData.life=1;scene.add(r);ripples.push(r)}
function splash(p,n=1){ripple(p);for(let i=0;i<8*n;i++){const d=new THREE.Mesh(new THREE.SphereGeometry(.015,5,4),new THREE.MeshBasicMaterial({color:0xc9f8ff,transparent:true}));d.position.copy(p);d.userData={life:.6+Math.random()*.5,v:new THREE.Vector3((Math.random()-.5)*n,Math.random()*1.4*n,(Math.random()-.5)*n)};scene.add(d);drops.push(d)}}
function mission(rec){if(st.mission.complete)return;let done=false;if(st.mission.id==='species'){st.species.add(rec.name);done=st.species.size>=3}if(st.mission.id==='heavy')done=rec.weight>=8;if(st.mission.id==='clean')done=st.maxT<.82;if(st.mission.id==='night')done=wx().name==='Night Glass';if(done){st.mission.complete=true;st.coins+=st.mission.reward;msg(`MISSION COMPLETE +${st.mission.reward}`,5);tone(1080,.3,.09)}}
function land(){const d=st.fish.userData;st.phase='landed';st.coins+=Math.round(d.s.v*d.w);st.xp+=Math.round(d.w*12);const rec={name:d.s.name,weight:d.w,time:new Date().toISOString(),weather:wx().name,bait:BAITS[st.bait].name};st.catches.push(rec);if(!st.best||d.w>st.best.weight)st.best=rec;mission(rec);msg(`LANDED ${d.s.name} • ${d.w.toFixed(1)} lb`,5);haptic(1,220);scene.remove(st.fish);fish.splice(fish.indexOf(st.fish),1);setTimeout(()=>spawn(Date.now()%7),1200);save();hud()}
function escape(t){msg(t,2.5);haptic(.6,140);st.phase='idle';st.fish=null;bobber.visible=false;q('#tension-wrap').classList.remove('show')}
function casting(dt){if(st.phase!=='casting')return;st.castV.y-=9.81*dt;bobber.position.addScaledVector(st.castV,dt);if(bobber.position.y<=.08){bobber.position.y=.08;if(Math.hypot(bobber.position.x,bobber.position.z)>W.pond-1){const a=Math.atan2(bobber.position.z,bobber.position.x);bobber.position.set(Math.cos(a)*(W.pond-1),.08,Math.sin(a)*(W.pond-1))}st.phase='waiting';splash(bobber.position,1.4);msg('Waiting for a bite…')}}
function swim(dt){for(const f of fish){if(f===st.fish&&st.phase==='fight')continue;const d=f.userData;d.wander+=dt;d.turn+=(Math.random()-.5)*dt*.34;d.turn*=.98;d.h+=d.turn*dt+Math.sin(d.wander*.3)*dt*.05;f.rotation.y=-d.h;f.position.x+=Math.cos(d.h)*d.spd*dt;f.position.z+=Math.sin(d.h)*d.spd*dt;f.position.y+=Math.sin(d.wander*1.3)*dt*.03;d.tail.rotation.y=Math.sin(st.time*7+d.wander)*.42;if(Math.hypot(f.position.x,f.position.z)>W.pond-1.2)d.h+=Math.PI*.75;if(st.phase==='waiting'){const dist=Math.hypot(f.position.x-bobber.position.x,f.position.z-bobber.position.z),b=BAITS[st.bait],compat=d.s.bait[st.bait];if(dist<4.2){d.int+=dt*b.a*compat*wx().bite*(.45+Math.max(0,1-dist/4.5));const tar=tmp.copy(bobber.position);tar.y=-Math.max(.25,b.s*6);f.position.lerp(tar,.075*dt*b.a);if(d.int>1.5+Math.random()*2){st.phase='bite';st.fish=f;st.bite=1.75;splash(bobber.position,.8);msg('BITE — SET THE HOOK!',1.8);haptic(.78,95)}}else d.int=Math.max(0,d.int-dt*.25)}}if(st.phase==='bite'){st.bite-=dt;bobber.position.y=.04+Math.sin(st.time*28)*.035;if(st.bite<=0)escape('Too slow — it dropped the bait')}}
function fight(dt){if(st.phase!=='fight'||!st.fish)return;const f=st.fish,d=f.userData,ls=1+.17*(st.line-1),rp=1+.14*(st.rod-1),re=1+.15*(st.reel-1);d.burst-=dt;if(d.burst<=0){d.burst=.45+Math.random()*1.4;d.turn+=(Math.random()-.5)*2.5;haptic(.45,55)}const surge=(.34+Math.abs(Math.sin(st.time*(1.4+d.s.p)))*.34+Math.random()*.13)*d.s.p;st.tension+=dt*(surge/ls-st.reeling*.76*rp-st.drag*.13);st.tension=THREE.MathUtils.clamp(st.tension,0,1.28);st.maxT=Math.max(st.maxT,st.tension);if(st.reeling){d.stam-=dt*(.095+.026*st.rod)*re*(1.18-st.tension*.35);const to=tmp.copy(player.position);to.y=f.position.y;to.sub(f.position).normalize();f.position.addScaledVector(to,dt*(.34+.09*st.reel));reel.rotation.x+=dt*14*re}else d.stam=Math.min(1,d.stam+dt*.03);d.h+=d.turn*dt;f.position.x+=Math.cos(d.h)*surge*dt*.34;f.position.z+=Math.sin(d.h)*surge*dt*.34;d.tail.rotation.y=Math.sin(st.time*16)*.65;bobber.position.copy(f.position);bobber.position.y=.08;q('#tension-fill').style.width=`${Math.min(100,st.tension*100)}%`;q('#tension-fill').style.background=st.tension>.82?'#ff4f57':st.tension<.2?'#f6c85f':'#59e2b6';if(Math.random()<dt*3)splash(bobber.position,.45);if(st.tension>1.02){escape('Line snapped under too much tension');return}if(st.tension<.05&&Math.random()<dt*.3){escape('The hook went slack');return}if(d.stam<=0&&Math.hypot(f.position.x-player.position.x,f.position.z-player.position.z)<4.3)land()}
function lineUpdate(){if(st.phase==='idle'||!bobber.visible){line.visible=false;return}line.visible=true;const a=new THREE.Vector3();tip.getWorldPosition(a);const pts=[];for(let i=0;i<=16;i++){const t=i/16,p=a.clone().lerp(bobber.position,t);p.y-=Math.sin(Math.PI*t)*Math.min(1.4,a.distanceTo(bobber.position)*.048)*(st.phase==='fight'?.18:1);pts.push(p)}line.geometry.setFromPoints(pts)}
function rodPose(){if(renderer.xr.isPresenting){gripR.getWorldPosition(tmp);gripR.getWorldQuaternion(quat);if(rod.parent!==scene){rod.parent?.remove(rod);scene.add(rod)}rod.position.copy(tmp);rod.quaternion.copy(quat);rod.rotateZ(-Math.PI/2);rod.position.y-=.05}}
function reelGesture(){if(!renderer.xr.isPresenting)return;const l=new THREE.Vector3(),r=new THREE.Vector3();gripL.getWorldPosition(l);gripR.getWorldPosition(r);const rel=l.sub(r),ang=Math.atan2(rel.y,rel.z);if(st.lastAngle!=null){let d=ang-st.lastAngle;if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;if(Math.abs(d)>.025&&rel.length()<.65){st.reeling=1;reel.rotation.x+=d*5;haptic(.08,12,true)}else if(!ctlR?.userData?.gamepad?.buttons?.[1]?.pressed)st.reeling=0}st.lastAngle=ang}
function move(dt){const ses=renderer.xr.getSession();if(!ses)return;let moving=0;for(const s of ses.inputSources){if(!s.gamepad)continue;const a=s.gamepad.axes;if(s.handedness==='left'&&a.length>=4){const x=a[2]||0,y=a[3]||0;camera.getWorldDirection(tmp);tmp.y=0;tmp.normalize();tmp2.set(1,0,0).applyQuaternion(camera.quaternion);tmp2.y=0;tmp2.normalize();player.position.addScaledVector(tmp,-y*dt*2.2);player.position.addScaledVector(tmp2,x*dt*2.2);moving=Math.max(Math.abs(x),Math.abs(y));if(player.position.length()>42)player.position.setLength(42)}if(s.handedness==='right'&&a.length>=4&&st.time-st.lastSnap>.35){const x=a[2]||0;if(Math.abs(x)>.75){player.rotation.y-=Math.sign(x)*THREE.MathUtils.degToRad(30);st.lastSnap=st.time;haptic(.25,35)}}}vignette.material.opacity=THREE.MathUtils.lerp(vignette.material.opacity,moving*.55,.18)}
function worldUpdate(dt){st.time+=dt;const w=wx(),phi=THREE.MathUtils.degToRad(90-(.18+st.time*.00045)%1*150),sp=new THREE.Vector3().setFromSphericalCoords(1,phi,Math.PI);sky.material.uniforms.sunPosition.value.copy(sp);sun.position.copy(sp).multiplyScalar(44);water.material.uniforms.sunDirection.value.copy(sun.position).normalize();water.material.uniforms.time.value+=dt*(.55+w.wind);water.material.uniforms.waterColor.value.setHex(w.water);renderer.toneMappingExposure=.48+THREE.MathUtils.clamp(sp.y*.8+.35,.12,1)*w.light*.72;scene.fog.color.setHex(w.fog);scene.background=scene.fog.color;scene.fog.density=.01+w.wind*.006;for(const b of birds){const d=b.userData,a=st.time*d.s+d.p;b.position.set(Math.cos(a)*d.r,d.h+Math.sin(a*2)*.5,Math.sin(a)*d.r);b.rotation.y=-a}for(const b of bugs){const d=b.userData,t=st.time+d.p;b.position.set(d.c.x+Math.sin(t*1.7)*.5,d.c.y+Math.sin(t*2.6)*.25,d.c.z+Math.cos(t*1.3)*.5)}for(const r of reeds)r.rotation.z=Math.sin(st.time*(.8+w.wind)+r.userData.p)*(.03+w.wind*.08)}
function effects(dt){for(let i=ripples.length-1;i>=0;i--){const r=ripples[i];r.userData.life-=dt;r.scale.multiplyScalar(1+dt*1.6);r.material.opacity=Math.max(0,r.userData.life*.75);if(r.userData.life<=0){scene.remove(r);ripples.splice(i,1)}}for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.userData.life-=dt;d.userData.v.y-=3.2*dt;d.position.addScaledVector(d.userData.v,dt);d.material.opacity=Math.max(0,d.userData.life);if(d.userData.life<=0){scene.remove(d);drops.splice(i,1)}}}
function loop(){const dt=Math.min(clock.getDelta(),.045);st.cool=Math.max(0,st.cool-dt);if(st.msg>0&&(st.msg-=dt)<=0)q('#status').classList.remove('show');rodPose();reelGesture();move(dt);worldUpdate(dt);casting(dt);swim(dt);fight(dt);effects(dt);lineUpdate();renderer.render(scene,camera)}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}
q('#start').addEventListener('click',init);q('#reset').addEventListener('click',()=>{if(confirm('Reset fishing progress?')){localStorage.clear();location.reload()}});q('#weather-cycle')?.addEventListener('click',cycleWeather);q('#drag-down')?.addEventListener('click',()=>drag(-.05));q('#drag-up')?.addEventListener('click',()=>drag(.05));