#!/usr/bin/env python3
"""
TLS Certificate Expiry Monitor — connects to each host:port on an interval,
reads the server's TLS certificate, and fires a webhook when a certificate is
within N days of expiring. Generated by the Aether Worker Foundry. Stdlib only
(ssl + socket).
"""
from __future__ import annotations
import argparse, datetime, json, socket, ssl, sys, time
import urllib.request

_FMT = "%b %d %H:%M:%S %Y %Z"


def check(host, port, timeout):
    ctx = ssl.create_default_context()
    with socket.create_connection((host, port), timeout=timeout) as sock:
        with ctx.wrap_socket(sock, server_hostname=host) as ssock:
            cert = ssock.getpeercert()
    not_after = datetime.datetime.strptime(cert["notAfter"], _FMT).replace(tzinfo=datetime.timezone.utc)
    days_left = (not_after - datetime.datetime.now(datetime.timezone.utc)).days
    return {"host": host, "port": port, "not_after": cert["notAfter"], "days_left": days_left,
            "subject": dict(x[0] for x in cert.get("subject", []))}


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hosts", default="{{HOSTS}}", help="comma-separated host[:port] (default port 443)")
    ap.add_argument("--warn-days", type=int, default={{WARN_DAYS}})
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--webhook", default="{{WEBHOOK}}")
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()
    targets = []
    for h in a.hosts.split(","):
        h = h.strip()
        if not h:
            continue
        if ":" in h:
            host, port = h.rsplit(":", 1)
            targets.append((host, int(port)))
        else:
            targets.append((h, 443))

    while True:
        for host, port in targets:
            try:
                rec = check(host, port, 10)
            except Exception as e:
                rec = {"host": host, "port": port, "error": str(e)}
                print(json.dumps(rec)); sys.stdout.flush()
                continue
            rec["ts"] = time.time()
            expiring = rec["days_left"] <= a.warn_days
            if expiring:
                rec["alert"] = "expiring_soon"
            print(json.dumps(rec)); sys.stdout.flush()
            if expiring and a.webhook:
                try: post(a.webhook, rec)
                except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
        if a.once:
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
