#!/usr/bin/env python3
"""
Keyword Alert — polls a list of pages on an interval, scans the text for any
of your keywords, and fires a webhook the first time each (url, keyword) pair
is seen. Generated by the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, re, sys, time
import urllib.request

_TAG = re.compile(r"<[^>]+>")


def fetch_text(url, timeout):
    req = urllib.request.Request(url, headers={"User-Agent": "AetherKeywordAlert/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        html = r.read(2_000_000).decode("utf-8", "replace")
    return _TAG.sub(" ", html)


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--urls", default="{{URLS}}")
    ap.add_argument("--keywords", default="{{KEYWORDS}}")
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--webhook", default="{{WEBHOOK}}")
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()
    urls = [u.strip() for u in a.urls.split(",") if u.strip()]
    keywords = [k.strip() for k in a.keywords.split(",") if k.strip()]
    seen = set()
    while True:
        for u in urls:
            try:
                text = fetch_text(u, 20).lower()
            except Exception as e:
                print(json.dumps({"url": u, "error": str(e)}), file=sys.stderr)
                continue
            for kw in keywords:
                key = (u, kw.lower())
                if kw.lower() in text and key not in seen:
                    seen.add(key)
                    rec = {"url": u, "keyword": kw, "ts": time.time()}
                    print(json.dumps(rec)); sys.stdout.flush()
                    if a.webhook:
                        try: post(a.webhook, rec)
                        except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
        if a.once:
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
