#!/usr/bin/env node
/**
 * Visual Diff — headless Chromium via Playwright. Screenshots two URLs (e.g.
 * staging vs prod, or before/after a deploy) and computes a pixel-level diff
 * entirely inside the browser's own canvas (no image libraries). Writes a
 * diff.png highlighting changed pixels and prints the diff percentage.
 * Generated by the Aether Worker Foundry.
 *
 *   npm i playwright   # once
 *   node visualdiff.js --url-a https://staging.example.com --url-b https://example.com
 */
'use strict';
const fs = require('fs');

function arg(name, def) {
  const i = process.argv.indexOf('--' + name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

async function launch(chromium) {
  try { return await chromium.launch({ headless: true }); }
  catch (e) {
    const exe = process.env.PLAYWRIGHT_CHROMIUM || '/opt/pw-browsers/chromium';
    return await chromium.launch({ headless: true, executablePath: exe });
  }
}

(async () => {
  const { chromium } = require('playwright');
  const urlA = arg('url-a', '{{URL_A}}');
  const urlB = arg('url-b', '{{URL_B}}');
  const width = parseInt(arg('width', '{{WIDTH}}'), 10);
  const threshold = parseInt(arg('threshold', '20'), 10);
  const outFile = arg('out', 'diff.png');

  const browser = await launch(chromium);
  const ctx = await browser.newContext({ viewport: { width, height: Math.round(width * 0.75) } });

  async function shotB64(url) {
    const page = await ctx.newPage();
    await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
    const buf = await page.screenshot({ fullPage: false });
    await page.close();
    return buf.toString('base64');
  }

  const [a, b] = await Promise.all([shotB64(urlA), shotB64(urlB)]);

  // Do the actual pixel comparison inside a real browser page, via <canvas>.
  const blank = await ctx.newPage();
  const diff = await blank.evaluate(async ({ a, b, threshold }) => {
    function loadImg(dataUrl) {
      return new Promise((resolve, reject) => {
        const img = new Image();
        img.onload = () => resolve(img);
        img.onerror = reject;
        img.src = dataUrl;
      });
    }
    const [imgA, imgB] = await Promise.all([loadImg('data:image/png;base64,' + a), loadImg('data:image/png;base64,' + b)]);
    const w = Math.max(imgA.width, imgB.width), h = Math.max(imgA.height, imgB.height);
    const ca = document.createElement('canvas'); ca.width = w; ca.height = h;
    const cb = document.createElement('canvas'); cb.width = w; cb.height = h;
    const out = document.createElement('canvas'); out.width = w; out.height = h;
    const gxa = ca.getContext('2d'), gxb = cb.getContext('2d'), gxo = out.getContext('2d');
    gxa.drawImage(imgA, 0, 0); gxb.drawImage(imgB, 0, 0);
    const da = gxa.getImageData(0, 0, w, h), db = gxb.getImageData(0, 0, w, h);
    const dout = gxo.createImageData(w, h);
    let diffPixels = 0;
    for (let i = 0; i < da.data.length; i += 4) {
      const dr = Math.abs(da.data[i] - db.data[i]);
      const dg = Math.abs(da.data[i + 1] - db.data[i + 1]);
      const db_ = Math.abs(da.data[i + 2] - db.data[i + 2]);
      const changed = (dr + dg + db_) / 3 > threshold;
      if (changed) {
        diffPixels++;
        dout.data[i] = 255; dout.data[i + 1] = 0; dout.data[i + 2] = 0; dout.data[i + 3] = 255;
      } else {
        dout.data[i] = da.data[i]; dout.data[i + 1] = da.data[i + 1];
        dout.data[i + 2] = da.data[i + 2]; dout.data[i + 3] = 60;
      }
    }
    gxo.putImageData(dout, 0, 0);
    const totalPixels = w * h;
    return {
      width: w, height: h, totalPixels, diffPixels,
      diffPercent: totalPixels ? +(100 * diffPixels / totalPixels).toFixed(3) : 0,
      diffPngDataUrl: out.toDataURL('image/png'),
    };
  }, { a, b, threshold });

  await blank.close();
  await browser.close();

  const pngBase64 = diff.diffPngDataUrl.split(',')[1];
  fs.writeFileSync(outFile, Buffer.from(pngBase64, 'base64'));
  delete diff.diffPngDataUrl;
  console.log(JSON.stringify({ url_a: urlA, url_b: urlB, out: outFile, ...diff }));
})().catch((e) => { console.error(e); process.exit(1); });
