#!/usr/bin/env python3
"""
RSS / Atom Feed Poller — polls feeds on an interval and emits only NEW items
(dedup by id/link across runs, persisted to a state file). Optionally POSTs
new items to a webhook. Generated by the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, os, re, sys, time
import urllib.request
import xml.etree.ElementTree as ET

STATE = ".rss_seen.json"


def strip_ns(tag): return tag.rsplit("}", 1)[-1].lower()


def parse_items(xml_bytes):
    items = []
    try:
        root = ET.fromstring(xml_bytes)
    except ET.ParseError:
        return items
    for el in root.iter():
        if strip_ns(el.tag) in ("item", "entry"):
            d = {}
            for c in el:
                t = strip_ns(c.tag)
                if t in ("title", "link", "id", "guid", "updated", "published", "pubdate"):
                    d[t] = (c.text or c.attrib.get("href", "")).strip()
            key = d.get("id") or d.get("guid") or d.get("link") or d.get("title")
            if key:
                d["_key"] = key
                items.append(d)
    return items


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--feeds", default="{{FEEDS}}")
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--webhook", default="{{WEBHOOK}}")
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()
    feeds = [f.strip() for f in a.feeds.split(",") if f.strip()]

    seen = set()
    if os.path.exists(STATE):
        try: seen = set(json.load(open(STATE)))
        except Exception: pass

    while True:
        for feed in feeds:
            try:
                with urllib.request.urlopen(urllib.request.Request(
                        feed, headers={"User-Agent": "AetherRSS/1.0"}), timeout=20) as r:
                    items = parse_items(r.read())
            except Exception as e:
                print(json.dumps({"feed": feed, "error": str(e)}), file=sys.stderr); continue
            for it in items:
                if it["_key"] in seen:
                    continue
                seen.add(it["_key"])
                out = {"feed": feed, "title": it.get("title"), "link": it.get("link")}
                print(json.dumps(out)); sys.stdout.flush()
                if a.webhook:
                    try: post(a.webhook, out)
                    except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
        json.dump(list(seen)[-5000:], open(STATE, "w"))
        if a.once:
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
