#!/usr/bin/env python3
"""
HTTP Batch Caller — reads a JSONL of requests and fires them with a bounded
thread pool + retry, writing one response line each. Generated by the Aether
Worker Foundry. Stdlib only.

Input line shape: {"method":"GET","url":"...","headers":{},"body":null,"id":"opt"}
"""
from __future__ import annotations
import argparse, json, sys, time
from concurrent.futures import ThreadPoolExecutor
import urllib.request


def call(req_spec, timeout, retries):
    method = (req_spec.get("method") or "GET").upper()
    url = req_spec["url"]
    data = req_spec.get("body")
    if data is not None and not isinstance(data, (bytes, bytearray)):
        data = json.dumps(data).encode()
    headers = req_spec.get("headers") or {}
    last = None
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(url, data=data, headers=headers, method=method)
            with urllib.request.urlopen(req, timeout=timeout) as r:
                body = r.read(1_000_000).decode("utf-8", "replace")
                return {"id": req_spec.get("id"), "url": url, "status": r.status, "body": body}
        except Exception as e:
            last = str(e)
            time.sleep(min(8.0, 0.5 * (2 ** attempt)))
    return {"id": req_spec.get("id"), "url": url, "status": None, "error": last}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="{{INPUT}}")
    ap.add_argument("--concurrency", type=int, default={{CONCURRENCY}})
    ap.add_argument("--timeout", type=float, default=30.0)
    ap.add_argument("--retries", type=int, default=2)
    a = ap.parse_args()

    reqs = []
    src = sys.stdin if a.input == "-" else open(a.input)
    for line in src:
        line = line.strip()
        if line:
            reqs.append(json.loads(line))

    with ThreadPoolExecutor(max_workers=a.concurrency) as pool:
        for res in pool.map(lambda r: call(r, a.timeout, a.retries), reqs):
            print(json.dumps(res)); sys.stdout.flush()


if __name__ == "__main__":
    main()
