#!/usr/bin/env python3
"""
Web Spider — breadth-first, same-domain crawler. Generated by the Aether
Worker Foundry. Stdlib only; respects robots.txt and rate-limits.

Writes one JSON object per line to stdout: {url, status, title, n_links}.
"""
from __future__ import annotations
import argparse, json, re, sys, time
from collections import deque
from urllib.parse import urljoin, urlsplit, urldefrag
from urllib.robotparser import RobotFileParser
import urllib.request

_TITLE = re.compile(r"<title[^>]*>(.*?)</title>", re.I | re.S)
_HREF = re.compile(r'href=["\']([^"\']+)["\']', re.I)


def fetch(url, timeout):
    req = urllib.request.Request(url, headers={"User-Agent": "AetherSpider/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        ctype = r.headers.get("Content-Type", "")
        body = r.read(2_000_000) if "html" in ctype else b""
        return r.status, body.decode("utf-8", "replace")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--start-url", default="{{START_URL}}")
    ap.add_argument("--max-pages", type=int, default={{MAX_PAGES}})
    ap.add_argument("--delay", type=float, default={{DELAY}})
    ap.add_argument("--timeout", type=float, default=15.0)
    a = ap.parse_args()

    origin = urlsplit(a.start_url)
    host = origin.netloc
    rp = RobotFileParser()
    try:
        rp.set_url(f"{origin.scheme}://{host}/robots.txt"); rp.read()
    except Exception:
        pass

    seen, seq = set(), deque([a.start_url])
    n = 0
    while seq and n < a.max_pages:
        url = urldefrag(seq.popleft())[0]
        if url in seen:
            continue
        seen.add(url)
        if rp.default_entry is not None and not rp.can_fetch("AetherSpider/1.0", url):
            continue
        try:
            status, html = fetch(url, a.timeout)
        except Exception as e:
            print(json.dumps({"url": url, "status": None, "error": str(e)})); continue
        title = (_TITLE.search(html).group(1).strip() if _TITLE.search(html) else "")[:200]
        links = []
        for m in _HREF.findall(html):
            nxt = urljoin(url, m)
            if urlsplit(nxt).netloc == host and nxt not in seen:
                links.append(nxt); seq.append(nxt)
        n += 1
        print(json.dumps({"url": url, "status": status, "title": title, "n_links": len(links)}))
        sys.stdout.flush()
        time.sleep(a.delay)
    print(json.dumps({"done": True, "crawled": n}), file=sys.stderr)


if __name__ == "__main__":
    main()
