#!/usr/bin/env python3
"""
CSV Merger — joins two CSV files on a key column (like a SQL join) and writes
merged records as JSONL. Supports inner and left joins. Generated by the
Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, csv, json, sys


def load(path, key):
    with open(path, newline="") as f:
        rows = list(csv.DictReader(f))
    by_key = {}
    for r in rows:
        by_key.setdefault(r.get(key), []).append(r)
    return by_key


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--left", default="{{LEFT}}")
    ap.add_argument("--right", default="{{RIGHT}}")
    ap.add_argument("--key", default="{{KEY}}")
    ap.add_argument("--how", default="{{HOW}}", choices=["inner", "left"])
    a = ap.parse_args()

    left = load(a.left, a.key)
    right = load(a.right, a.key)

    n = 0
    for k, lrows in left.items():
        matches = right.get(k, [])
        if matches:
            for lr in lrows:
                for rr in matches:
                    merged = {**lr, **{f"right_{c}": v for c, v in rr.items()}}
                    print(json.dumps(merged)); n += 1
        elif a.how == "left":
            for lr in lrows:
                print(json.dumps(lr)); n += 1

    print(json.dumps({"merged_rows": n, "how": a.how}), file=sys.stderr)


if __name__ == "__main__":
    main()
