#!/usr/bin/env python3
"""
Backup Worker — tars+gzips a directory on an interval into timestamped
archives, keeps only the last N, and optionally uploads each archive to an
HTTP endpoint. Generated by the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, os, sys, tarfile, time
import urllib.request


def make_archive(src, outdir):
    os.makedirs(outdir, exist_ok=True)
    stamp = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    name = f"backup-{stamp}.tar.gz"
    path = os.path.join(outdir, name)
    with tarfile.open(path, "w:gz") as tar:
        tar.add(src, arcname=os.path.basename(os.path.normpath(src)))
    return path


def rotate(outdir, keep):
    files = sorted(
        (f for f in os.listdir(outdir) if f.startswith("backup-") and f.endswith(".tar.gz")),
        reverse=True,
    )
    removed = []
    for f in files[keep:]:
        fp = os.path.join(outdir, f)
        try:
            os.remove(fp); removed.append(f)
        except OSError:
            pass
    return removed


def upload(url, path):
    with open(path, "rb") as f:
        data = f.read()
    req = urllib.request.Request(url, data=data, method="POST",
                                 headers={"Content-Type": "application/gzip",
                                          "X-Filename": os.path.basename(path)})
    with urllib.request.urlopen(req, timeout=120) as r:
        return r.status


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="{{DIR}}")
    ap.add_argument("--outdir", default="{{OUTDIR}}")
    ap.add_argument("--keep", type=int, default={{KEEP}})
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--upload", default="{{UPLOAD_URL}}")
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()

    while True:
        t0 = time.time()
        path = make_archive(a.dir, a.outdir)
        size = os.path.getsize(path)
        rec = {"archive": path, "bytes": size, "elapsed_s": round(time.time() - t0, 3)}
        if a.upload:
            try:
                rec["upload_status"] = upload(a.upload, path)
            except Exception as e:
                rec["upload_error"] = str(e)
        rec["removed"] = rotate(a.outdir, a.keep)
        print(json.dumps(rec)); sys.stdout.flush()
        if a.once:
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
