#!/usr/bin/env node
/**
 * Browser Automation (scripted DevTools) — runs a JSON action script and
 * captures console logs + network requests the way the DevTools panels do.
 * Generated by the Aether Worker Foundry.
 *
 * Actions (array, run in order):
 *   {"goto":"https://..."}         {"click":"css"}      {"type":["css","text"]}
 *   {"wait":1500}                  {"waitFor":"css"}    {"eval":"js expression"}
 *   {"screenshot":"out.png"}
 *
 *   npm i playwright
 *   node automate.js --start https://example.com --script '[{"eval":"document.title"}]'
 */
'use strict';
function arg(name, def) {
  const i = process.argv.indexOf('--' + name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
}
async function launch(chromium) {
  try { return await chromium.launch({ headless: true }); }
  catch { return await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM || '/opt/pw-browsers/chromium' }); }
}

(async () => {
  const { chromium } = require('playwright');
  const start = arg('start', '{{START_URL}}');
  const script = JSON.parse(arg('script', '{{SCRIPT}}'));

  const browser = await launch(chromium);
  const page = await browser.newPage();

  const consoleLogs = [];
  const network = [];
  page.on('console', (m) => consoleLogs.push({ type: m.type(), text: m.text() }));
  page.on('request', (r) => network.push({ method: r.method(), url: r.url() }));
  page.on('response', (r) => { const e = network.find(n => n.url === r.url() && !n.status); if (e) e.status = r.status(); });

  const results = [];
  await page.goto(start, { waitUntil: 'domcontentloaded', timeout: 30000 });
  for (const step of script) {
    try {
      if (step.goto) await page.goto(step.goto, { waitUntil: 'domcontentloaded', timeout: 30000 });
      else if (step.click) await page.click(step.click, { timeout: 15000 });
      else if (step.type) await page.fill(step.type[0], step.type[1]);
      else if (step.wait) await page.waitForTimeout(step.wait);
      else if (step.waitFor) await page.waitForSelector(step.waitFor, { timeout: 15000 });
      else if (step.screenshot) await page.screenshot({ path: step.screenshot, fullPage: true });
      else if (step.eval) results.push({ eval: step.eval, value: await page.evaluate(step.eval) });
      results.push({ step, ok: true });
    } catch (e) {
      results.push({ step, ok: false, error: String(e.message || e) });
    }
  }

  console.log(JSON.stringify({
    start, url: page.url(), results,
    console: consoleLogs, network: network.slice(0, 200),
  }, null, 2));
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
