#!/usr/bin/env python3
"""
Sitemap Crawler — fetches sitemap.xml (following nested <sitemapindex>),
then records HTTP status + last-modified for every listed URL. Generated by
the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, re, sys
import urllib.request

_LOC = re.compile(r"<loc>\s*(.*?)\s*</loc>", re.I | re.S)


def get(url, timeout):
    req = urllib.request.Request(url, headers={"User-Agent": "AetherSitemap/1.0"})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return r.status, r.read().decode("utf-8", "replace"), r.headers


def collect_urls(sitemap, timeout, depth=0):
    """Return page URLs, expanding sitemap-index files one level deep."""
    try:
        _, body, _ = get(sitemap, timeout)
    except Exception as e:
        print(json.dumps({"sitemap": sitemap, "error": str(e)}), file=sys.stderr)
        return []
    locs = _LOC.findall(body)
    if "<sitemapindex" in body.lower() and depth < 3:
        urls = []
        for sm in locs:
            urls += collect_urls(sm, timeout, depth + 1)
        return urls
    return locs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sitemap", default="{{SITEMAP}}")
    ap.add_argument("--timeout", type=float, default=15.0)
    ap.add_argument("--head-only", action="store_true", default=True)
    a = ap.parse_args()

    urls = collect_urls(a.sitemap, a.timeout)
    print(json.dumps({"sitemap": a.sitemap, "urls_found": len(urls)}), file=sys.stderr)
    for u in urls:
        try:
            req = urllib.request.Request(u, method="HEAD", headers={"User-Agent": "AetherSitemap/1.0"})
            with urllib.request.urlopen(req, timeout=a.timeout) as r:
                print(json.dumps({"url": u, "status": r.status,
                                  "last_modified": r.headers.get("Last-Modified")}))
        except Exception as e:
            print(json.dumps({"url": u, "status": None, "error": str(e)}))
        sys.stdout.flush()


if __name__ == "__main__":
    main()
