#!/usr/bin/env python3
"""
Distributed Map — reads a JSONL of items, applies handle() to every item across
a thread pool, and writes one result per line plus a final reduce() summary to
stderr. Drop your logic into handle()/reduce(). Generated by the Aether Worker
Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, sys, time
from concurrent.futures import ThreadPoolExecutor, as_completed


def handle(item: dict) -> dict:
    """Edit me. Runs once per input item, on a worker thread."""
    return {"echo": item}


def reduce(results: list[dict]) -> dict:
    """Edit me. Runs once, after every item has been handled."""
    return {"n": len(results)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="{{INPUT}}")
    ap.add_argument("--concurrency", type=int, default={{CONCURRENCY}})
    a = ap.parse_args()

    src = sys.stdin if a.input == "-" else open(a.input)
    items = [json.loads(l) for l in src if l.strip()]

    t0 = time.time()
    results = []
    with ThreadPoolExecutor(max_workers=a.concurrency) as pool:
        futs = {pool.submit(handle, it): i for i, it in enumerate(items)}
        for fut in as_completed(futs):
            i = futs[fut]
            try:
                res = fut.result()
            except Exception as e:
                res = {"error": str(e)}
            res["_index"] = i
            results.append(res)
            print(json.dumps(res)); sys.stdout.flush()

    results.sort(key=lambda r: r["_index"])
    summary = reduce(results)
    summary["elapsed_s"] = round(time.time() - t0, 3)
    summary["items"] = len(items)
    print(json.dumps({"summary": summary}), file=sys.stderr)


if __name__ == "__main__":
    main()
