#!/usr/bin/env python3
"""
Moderation Worker (Claude) — reads a JSONL of texts and asks Claude to flag
each against a plain-language policy, writing {flagged, reason} per record
with bounded concurrency + retry. Generated by the Aether Worker Foundry.
Stdlib only (raw Messages API over HTTPS), so no `anthropic` package needed.

Input line: {"text": "...", "id": "optional"}
Requires:   ANTHROPIC_API_KEY in the environment.
"""
from __future__ import annotations
import argparse, json, os, sys, time
from concurrent.futures import ThreadPoolExecutor
import urllib.request

API = "https://api.anthropic.com/v1/messages"


def moderate(text, policy, model, retries):
    key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not key:
        return {"error": "ANTHROPIC_API_KEY not set"}
    system = (
        "You are a content moderator. Policy: " + policy + " "
        "Respond with ONLY a compact JSON object: "
        '{"flagged": true|false, "reason": "short reason"}. No other text.'
    )
    payload = {"model": model, "max_tokens": 150, "system": system,
               "messages": [{"role": "user", "content": text}]}
    body = json.dumps(payload).encode()
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(API, data=body, method="POST", headers={
                "content-type": "application/json",
                "x-api-key": key,
                "anthropic-version": "2023-06-01",
            })
            with urllib.request.urlopen(req, timeout=60) as r:
                data = json.loads(r.read())
            raw = "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text").strip()
            try:
                parsed = json.loads(raw)
                return {"flagged": bool(parsed.get("flagged")), "reason": parsed.get("reason", "")}
            except json.JSONDecodeError:
                return {"flagged": None, "raw": raw}
        except Exception as e:
            if attempt == retries:
                return {"error": str(e)}
            time.sleep(min(30.0, 1.0 * (2 ** attempt)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="{{INPUT}}")
    ap.add_argument("--policy", default="{{POLICY}}")
    ap.add_argument("--model", default="{{MODEL}}")
    ap.add_argument("--concurrency", type=int, default=4)
    ap.add_argument("--retries", type=int, default=3)
    a = ap.parse_args()

    src = sys.stdin if a.input == "-" else open(a.input)
    rows = [json.loads(l) for l in src if l.strip()]

    def work(row):
        res = moderate(row.get("text", ""), a.policy, a.model, a.retries)
        res["id"] = row.get("id")
        return res

    with ThreadPoolExecutor(max_workers=a.concurrency) as pool:
        for res in pool.map(work, rows):
            print(json.dumps(res)); sys.stdout.flush()


if __name__ == "__main__":
    main()
