#!/usr/bin/env node
/**
 * DOM Scraper — loads a page in a real browser (JS executes), then extracts
 * fields by CSS selector. The stuff you'd hand-do in DevTools, automated.
 * Generated by the Aether Worker Foundry.
 *
 * Selector syntax: "css" -> first match's text; "css@attr" -> attribute;
 * "css[]" -> array of all matches' text; "css[]@attr" -> array of attributes.
 *
 *   npm i playwright
 *   node scrape.js --url https://example.com --selectors '{"title":"h1","links":"a[]@href"}'
 */
'use strict';
function arg(name, def) {
  const i = process.argv.indexOf('--' + name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

async function launch(chromium) {
  try { return await chromium.launch({ headless: true }); }
  catch { return await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM || '/opt/pw-browsers/chromium' }); }
}

(async () => {
  const { chromium } = require('playwright');
  const url = arg('url', '{{URL}}');
  const selectors = JSON.parse(arg('selectors', '{{SELECTORS}}'));

  const browser = await launch(chromium);
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });

  const out = await page.evaluate((sel) => {
    const pick = (spec) => {
      let all = false, attr = null, css = spec;
      if (css.includes('@')) { const p = css.split('@'); css = p[0]; attr = p[1]; }
      if (css.endsWith('[]')) { all = true; css = css.slice(0, -2); }
      const nodes = Array.from(document.querySelectorAll(css));
      const val = (n) => attr ? n.getAttribute(attr) : (n.textContent || '').trim();
      return all ? nodes.map(val) : (nodes[0] ? val(nodes[0]) : null);
    };
    const r = {};
    for (const [k, spec] of Object.entries(sel)) r[k] = pick(spec);
    return r;
  }, selectors);

  console.log(JSON.stringify({ url, fields: out }, null, 2));
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
