#!/usr/bin/env python3
"""
Mesh Compute Node (HTTP, push) — exposes POST /compute/batch and computes any
assigned population range of a Kuramoto batch, returning the coherences. A
coordinator posts ranges to this node's URL. Generated by the Aether Worker
Foundry. Stdlib only — the math is a self-contained splitmix64 + mean-field
Kuramoto kernel (matches the platform's global-index seeding convention).
"""
from __future__ import annotations
import argparse, json, math, os
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlsplit

_MASK = (1 << 64) - 1
_NODE = os.environ.get("MESH_NODE_ID", f"http-node-{os.getpid()}")


def _sm64(s):
    s = (s + 0x9E3779B97F4A7C15) & _MASK
    z = s
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & _MASK
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & _MASK
    return (z ^ (z >> 31)), s


def _r01(s):
    z, s = _sm64(s)
    return (z >> 11) * (1.0 / (1 << 53)), s


def simulate_one(nodes, steps, coupling, dt, seed):
    s = (seed + 1) & _MASK
    ph, fr = [], []
    for _ in range(nodes):
        u, s = _r01(s); ph.append(2 * math.pi * u)
    for _ in range(nodes):
        u, s = _r01(s); fr.append(u - 0.5)
    for _ in range(steps):
        sx = sum(math.cos(p) for p in ph); sy = sum(math.sin(p) for p in ph)
        psi = math.atan2(sy, sx); r = math.hypot(sx, sy) / nodes
        for i in range(nodes):
            ph[i] = math.fmod(ph[i] + dt * (fr[i] + coupling * r * math.sin(psi - ph[i])), 2 * math.pi)
    sx = sum(math.cos(p) for p in ph); sy = sum(math.sin(p) for p in ph)
    return math.hypot(sx, sy) / nodes


def compute_range(spec):
    begin, end = int(spec["range_begin"]), int(spec["range_end"])
    nodes, steps = int(spec["nodes"]), int(spec["steps"])
    coupling, dt, seed = float(spec["coupling"]), float(spec["dt"]), int(spec["seed"])
    coh = [simulate_one(nodes, steps, coupling, dt, seed + p) for p in range(begin, end)]
    return {"node": _NODE, "range_begin": begin, "range_end": end, "coherences": coh}


class H(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"
    def log_message(self, *a): pass
    def _send(self, code, data):
        body = json.dumps(data).encode()
        self.send_response(code); self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body))); self.end_headers(); self.wfile.write(body)
    def do_GET(self):
        if urlsplit(self.path).path == "/health":
            self._send(200, {"node": _NODE, "status": "ready"})
        else:
            self._send(404, {"error": "not_found"})
    def do_POST(self):
        if urlsplit(self.path).path != "/compute/batch":
            self._send(404, {"error": "not_found"}); return
        n = int(self.headers.get("Content-Length", 0))
        try:
            self._send(200, compute_range(json.loads(self.rfile.read(n)) if n else {}))
        except Exception as e:
            self._send(500, {"node": _NODE, "error": str(e)})


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", default="0.0.0.0")
    ap.add_argument("--port", type=int, default={{PORT}})
    a = ap.parse_args()
    print(f"[mesh-http-worker {_NODE}] http://{a.host}:{a.port}/compute/batch")
    ThreadingHTTPServer((a.host, a.port), H).serve_forever()


if __name__ == "__main__":
    main()
