#!/usr/bin/env python3
"""
Uptime Monitor — pings a list of URLs on an interval, tracks up/down, and fires
a webhook ONLY on a state transition (not every check). Generated by the Aether
Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, sys, time
import urllib.request


def probe(url, timeout):
    t0 = time.time()
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "AetherUptime/1.0"})
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return (200 <= r.status < 400), r.status, round((time.time() - t0) * 1000)
    except Exception:
        return False, None, round((time.time() - t0) * 1000)


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--urls", default="{{URLS}}")
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--webhook", default="{{WEBHOOK}}")
    ap.add_argument("--timeout", type=float, default=10.0)
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()
    urls = [u.strip() for u in a.urls.split(",") if u.strip()]
    state = {}
    while True:
        for u in urls:
            up, status, ms = probe(u, a.timeout)
            prev = state.get(u)
            rec = {"url": u, "up": up, "status": status, "latency_ms": ms, "ts": time.time()}
            if prev is None or prev != up:
                rec["transition"] = "UP" if up else "DOWN"
                print(json.dumps(rec)); sys.stdout.flush()
                if a.webhook:
                    try: post(a.webhook, rec)
                    except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
            state[u] = up
        if a.once:
            print(json.dumps({"snapshot": state}))
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
