#!/usr/bin/env python3
"""
Embedding Worker — reads text lines and POSTs them to an embeddings endpoint in
batches, writing {text, vector} JSONL. Endpoint-agnostic: it expects the sink to
accept {"texts": [...]} and return {"vectors": [[...], ...]}. Generated by the
Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, sys, time
import urllib.request


def embed_batch(endpoint, texts, retries=3):
    body = json.dumps({"texts": texts}).encode()
    for attempt in range(retries + 1):
        try:
            req = urllib.request.Request(endpoint, data=body, method="POST",
                                         headers={"Content-Type": "application/json"})
            with urllib.request.urlopen(req, timeout=120) as r:
                return json.loads(r.read()).get("vectors", [])
        except Exception as e:
            if attempt == retries:
                raise
            time.sleep(min(20.0, 0.5 * (2 ** attempt)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="{{INPUT}}")
    ap.add_argument("--endpoint", default="{{ENDPOINT}}")
    ap.add_argument("--batch", type=int, default={{BATCH}})
    a = ap.parse_args()

    src = sys.stdin if a.input == "-" else open(a.input)
    texts = [ln.rstrip("\n") for ln in src if ln.strip()]
    done = 0
    for i in range(0, len(texts), a.batch):
        chunk = texts[i:i + a.batch]
        try:
            vectors = embed_batch(a.endpoint, chunk)
        except Exception as e:
            print(json.dumps({"batch_error": str(e), "at": i}), file=sys.stderr); continue
        for t, v in zip(chunk, vectors):
            print(json.dumps({"text": t, "vector": v})); done += 1
        sys.stdout.flush()
    print(json.dumps({"done": True, "embedded": done}), file=sys.stderr)


if __name__ == "__main__":
    main()
