#!/usr/bin/env python3
"""
JSON Diff Watcher — deep-diffs two JSON documents (files or URLs) and reports
every added/removed/changed path. Point BASELINE at a fixed snapshot and
CURRENT at a live source to catch config drift, or diff two arbitrary
documents one-shot. Generated by the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, sys
import urllib.request


def load(source):
    if source.startswith("http://") or source.startswith("https://"):
        req = urllib.request.Request(source, headers={"User-Agent": "AetherJSONDiff/1.0"})
        with urllib.request.urlopen(req, timeout=20) as r:
            return json.loads(r.read())
    with open(source) as f:
        return json.load(f)


def diff(a, b, path=""):
    out = []
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            p = f"{path}.{k}" if path else k
            if k not in a:
                out.append({"op": "add", "path": p, "value": b[k]})
            elif k not in b:
                out.append({"op": "remove", "path": p, "value": a[k]})
            else:
                out.extend(diff(a[k], b[k], p))
    elif isinstance(a, list) and isinstance(b, list):
        if a != b:
            out.append({"op": "change", "path": path or "$", "before": a, "after": b})
    else:
        if a != b:
            out.append({"op": "change", "path": path or "$", "before": a, "after": b})
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--baseline", default="{{BASELINE}}")
    ap.add_argument("--current", default="{{CURRENT}}")
    a = ap.parse_args()

    before = load(a.baseline)
    after = load(a.current)
    changes = diff(before, after)
    for c in changes:
        print(json.dumps(c))
    print(json.dumps({"summary": {"changes": len(changes)}}), file=sys.stderr)
    if changes:
        sys.exit(1)


if __name__ == "__main__":
    main()
