#!/usr/bin/env python3
"""
Schema Validator — validates a JSONL stream against a lightweight JSON Schema
subset (type, required, enum, minimum/maximum for numbers) with no third-party
`jsonschema` dependency. Splits input into VALID_OUT / INVALID_OUT, the latter
annotated with the failing reasons. Generated by the Aether Worker Foundry.
Stdlib only.
"""
from __future__ import annotations
import argparse, json, sys

_TYPES = {
    "string": str, "number": (int, float), "integer": int,
    "boolean": bool, "object": dict, "array": list,
}


def validate(rec, schema, path=""):
    errors = []
    props = schema.get("properties", {})
    for req in schema.get("required", []):
        if req not in rec:
            errors.append(f"{path}{req}: required field missing")
    for k, v in rec.items() if isinstance(rec, dict) else []:
        spec = props.get(k)
        if spec is None:
            continue
        t = spec.get("type")
        if t and t in _TYPES and not isinstance(v, _TYPES[t]):
            errors.append(f"{path}{k}: expected {t}, got {type(v).__name__}")
            continue
        if "enum" in spec and v not in spec["enum"]:
            errors.append(f"{path}{k}: {v!r} not in {spec['enum']}")
        if isinstance(v, (int, float)) and not isinstance(v, bool):
            if "minimum" in spec and v < spec["minimum"]:
                errors.append(f"{path}{k}: {v} < minimum {spec['minimum']}")
            if "maximum" in spec and v > spec["maximum"]:
                errors.append(f"{path}{k}: {v} > maximum {spec['maximum']}")
    return errors


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="{{INPUT}}")
    ap.add_argument("--schema", default='{{SCHEMA}}', help="JSON Schema object as a JSON string, or a path to one")
    ap.add_argument("--valid-out", default="{{VALID_OUT}}")
    ap.add_argument("--invalid-out", default="{{INVALID_OUT}}")
    a = ap.parse_args()

    try:
        schema = json.loads(a.schema)
    except json.JSONDecodeError:
        with open(a.schema) as f:
            schema = json.load(f)

    src = sys.stdin if a.input == "-" else open(a.input)
    valid_f = open(a.valid_out, "w")
    invalid_f = open(a.invalid_out, "w")

    total = ok = 0
    for line in src:
        line = line.strip()
        if not line:
            continue
        total += 1
        rec = json.loads(line)
        errors = validate(rec, schema)
        if errors:
            invalid_f.write(json.dumps({"record": rec, "errors": errors}) + "\n")
        else:
            ok += 1
            valid_f.write(line + "\n")

    valid_f.close(); invalid_f.close()
    print(json.dumps({"total": total, "valid": ok, "invalid": total - ok}), file=sys.stderr)


if __name__ == "__main__":
    main()
