#!/usr/bin/env node
/**
 * 📚 organism-docs-bot — Auto-Documentation Generator
 * ════════════════════════════════════════════════════
 *
 * Generates documentation from the living codebase:
 *  --extensions   Extension catalog from manifest.json files
 *  --protocols    Protocol encyclopedia from protocols JS files
 *  --sdks         SDK reference from sdk package.json files
 *  --architecture Full architecture map
 *
 * Usage:
 *   node scripts/generate-docs.js --extensions
 *   node scripts/generate-docs.js --protocols
 *   node scripts/generate-docs.js --sdks
 *   node scripts/generate-docs.js --architecture
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const DOCS = path.join(REPO, 'docs');

const flags = {
  extensions:   process.argv.includes('--extensions'),
  protocols:    process.argv.includes('--protocols'),
  sdks:         process.argv.includes('--sdks'),
  architecture: process.argv.includes('--architecture'),
};

// If no flags, do all
if (!Object.values(flags).some(Boolean)) {
  Object.keys(flags).forEach(k => flags[k] = true);
}

fs.mkdirSync(DOCS, { recursive: true });

// ── Extension Catalog ────────────────────────────────────────────────────────
function generateExtensionCatalog() {
  console.log('  📦 Generating extension catalog...');

  const extDir = path.join(REPO, 'extensions');
  if (!fs.existsSync(extDir)) { console.log('    ⚠ No extensions/ directory'); return; }

  const extensions = [];
  const dirs = fs.readdirSync(extDir, { withFileTypes: true }).filter(d => d.isDirectory());

  for (const dir of dirs) {
    const manifestPath = path.join(extDir, dir.name, 'manifest.json');
    if (!fs.existsSync(manifestPath)) continue;

    try {
      const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
      extensions.push({
        name: dir.name,
        displayName: manifest.name || dir.name,
        version: manifest.version || '?',
        description: manifest.description || '',
        permissions: manifest.permissions || [],
        manifestVersion: manifest.manifest_version || '?',
      });
    } catch {
      extensions.push({ name: dir.name, displayName: dir.name, version: '?', description: 'Invalid manifest', permissions: [], manifestVersion: '?' });
    }
  }

  const lines = [
    '# 📦 Extension Catalog',
    '',
    `> ${extensions.length} browser extensions — auto-generated by organism-docs-bot on ${new Date().toUTCString()}`,
    '',
    '| Extension | Version | Description | Permissions |',
    '|-----------|---------|-------------|-------------|',
    ...extensions.map(e => `| **${e.displayName}** | ${e.version} | ${e.description.slice(0, 80)} | ${e.permissions.slice(0, 3).join(', ')}${e.permissions.length > 3 ? '…' : ''} |`),
    '',
    '---',
    '*Generated by organism-docs-bot*',
  ];

  fs.writeFileSync(path.join(DOCS, 'extension-catalog.md'), lines.join('\n'));
  console.log(`    ✅ ${extensions.length} extensions cataloged`);
}

// ── Protocol Encyclopedia ────────────────────────────────────────────────────
function generateProtocolEncyclopedia() {
  console.log('  🔬 Generating protocol encyclopedia...');

  const protDir = path.join(REPO, 'protocols');
  if (!fs.existsSync(protDir)) { console.log('    ⚠ No protocols/ directory'); return; }

  const files = fs.readdirSync(protDir).filter(f => f.endsWith('.js') && f !== 'index.js');
  const protocols = [];

  for (const file of files) {
    const content = fs.readFileSync(path.join(protDir, file), 'utf8');
    const name = file.replace('.js', '');

    // Extract JSDoc or first comment block
    const commentMatch = content.match(/\/\*\*([\s\S]*?)\*\//);
    const description = commentMatch
      ? commentMatch[1].replace(/\s*\*\s*/g, ' ').trim().slice(0, 200)
      : '';

    const classes = (content.match(/class\s+(\w+)/g) || []).map(c => c.replace('class ', ''));

    protocols.push({ name, file, description, classes, lines: content.split('\n').length });
  }

  const lines = [
    '# 🔬 Protocol Encyclopedia',
    '',
    `> ${protocols.length} protocols — auto-generated by organism-docs-bot on ${new Date().toUTCString()}`,
    '',
    ...protocols.map(p => [
      `## ${p.name}`,
      '',
      p.description ? `> ${p.description}` : '',
      '',
      `- **File:** \`protocols/${p.file}\``,
      `- **Classes:** ${p.classes.join(', ') || 'none'}`,
      `- **Lines:** ${p.lines}`,
      '',
    ].join('\n')),
    '---',
    '*Generated by organism-docs-bot*',
  ];

  fs.writeFileSync(path.join(DOCS, 'protocol-encyclopedia.md'), lines.join('\n'));
  console.log(`    ✅ ${protocols.length} protocols documented`);
}

// ── SDK Reference ────────────────────────────────────────────────────────────
function generateSdkReference() {
  console.log('  📦 Generating SDK reference...');

  const sdkDir = path.join(REPO, 'sdk');
  if (!fs.existsSync(sdkDir)) { console.log('    ⚠ No sdk/ directory'); return; }

  const dirs = fs.readdirSync(sdkDir, { withFileTypes: true }).filter(d => d.isDirectory());
  const sdks = [];

  for (const dir of dirs) {
    const pkgPath = path.join(sdkDir, dir.name, 'package.json');
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
        sdks.push({
          name: pkg.name || dir.name,
          version: pkg.version || '?',
          description: pkg.description || '',
          main: pkg.main || 'index.js',
        });
      } catch {
        sdks.push({ name: dir.name, version: '?', description: 'Parse error', main: '?' });
      }
    } else {
      const files = fs.readdirSync(path.join(sdkDir, dir.name));
      sdks.push({ name: dir.name, version: 'source', description: `${files.length} files`, main: '—' });
    }
  }

  const lines = [
    '# 📦 SDK Reference',
    '',
    `> ${sdks.length} SDK modules — auto-generated by organism-docs-bot on ${new Date().toUTCString()}`,
    '',
    '| SDK | Version | Entry | Description |',
    '|-----|---------|-------|-------------|',
    ...sdks.map(s => `| **${s.name}** | ${s.version} | \`${s.main}\` | ${s.description.slice(0, 100)} |`),
    '',
    '---',
    '*Generated by organism-docs-bot*',
  ];

  fs.writeFileSync(path.join(DOCS, 'sdk-reference.md'), lines.join('\n'));
  console.log(`    ✅ ${sdks.length} SDKs documented`);
}

// ── Master Architecture Map ──────────────────────────────────────────────────
function generateArchitectureMap() {
  console.log('  🏗️  Generating architecture map...');

  const countFiles = (dir) => {
    if (!fs.existsSync(dir)) return 0;
    try {
      return fs.readdirSync(dir, { withFileTypes: true })
        .reduce((n, d) => n + (d.isDirectory() ? countFiles(path.join(dir, d.name)) : 1), 0);
    } catch { return 0; }
  };

  const countDirs = (dir) => {
    if (!fs.existsSync(dir)) return 0;
    return fs.readdirSync(dir, { withFileTypes: true }).filter(d => d.isDirectory()).length;
  };

  // Count CSV registers
  const csvFiles = fs.readdirSync(REPO).filter(f => f.endsWith('.csv'));

  const lines = [
    '# 🏗️ Sovereign Organism — Architecture Map',
    '',
    `> Auto-generated by organism-docs-bot on ${new Date().toUTCString()}`,
    '',
    '## System Overview',
    '',
    '```',
    'SOVEREIGN ORGANISM',
    '├── extensions/      Browser extensions (Chrome/Edge/Brave)',
    '├── sdk/             SDK modules (npm-publishable)',
    '├── protocols/       Intelligence protocols (neural, memory, routing)',
    '├── organism/        Multi-language runtimes (TS, Python, C++, Java, Motoko, Web)',
    '├── scripts/         Build & automation scripts',
    '├── test/            Test suites (CLI, SDK, Extensions)',
    '├── governance/      Legal & regulatory documents',
    '├── docs/            Generated documentation',
    '├── dist/            Build artifacts',
    '├── desktop/         Electron desktop app',
    '├── electron/        Electron shell',
    '└── workflows/       Native workflow definitions',
    '```',
    '',
    '## Metrics',
    '',
    '| Layer | Count |',
    '|-------|-------|',
    `| Browser Extensions | ${countDirs(path.join(REPO, 'extensions'))} |`,
    `| SDK Modules | ${countDirs(path.join(REPO, 'sdk'))} |`,
    `| Protocols | ${fs.existsSync(path.join(REPO, 'protocols')) ? fs.readdirSync(path.join(REPO, 'protocols')).filter(f => f.endsWith('.js') && f !== 'index.js').length : 0} |`,
    `| Organism Runtimes | ${countDirs(path.join(REPO, 'organism'))} |`,
    `| CSV Registers | ${csvFiles.length} |`,
    `| Test Suites | ${countDirs(path.join(REPO, 'test'))} |`,
    `| Governance Docs | ${countDirs(path.join(REPO, 'governance'))} |`,
    `| Build Scripts | ${fs.existsSync(path.join(REPO, 'scripts')) ? fs.readdirSync(path.join(REPO, 'scripts')).length : 0} |`,
    `| GitHub Workflows | ${fs.existsSync(path.join(REPO, '.github', 'workflows')) ? fs.readdirSync(path.join(REPO, '.github', 'workflows')).length : 0} |`,
    '',
    '## Organism Bot Fleet',
    '',
    '| Bot Identity | Domain | Trigger |',
    '|-------------|--------|---------|',
    '| organism-build-bot | Extension packaging | Push to extensions/ |',
    '| organism-neural-bot | Neural architecture validation | Push to protocols/ |',
    '| organism-sdk-bot | SDK validation & packaging | Push to sdk/ |',
    '| organism-protocol-bot | Protocol linting & graphing | Push to protocols/ |',
    '| organism-test-bot | Cross-matrix testing | Push to test/ |',
    '| organism-docs-bot | Documentation generation | Push to any source |',
    '| organism-release-bot | Production releases | Version tags |',
    '| organism-deploy-bot | ICP & Pages deployment | Push to organism/ |',
    '| organism-sentinel-bot | Security scanning | Weekly + push |',
    '',
    '---',
    '*Generated by organism-docs-bot*',
  ];

  fs.writeFileSync(path.join(DOCS, 'architecture-map.md'), lines.join('\n'));
  console.log('    ✅ Architecture map generated');
}

// ── Main ─────────────────────────────────────────────────────────────────────
function main() {
  console.log('');
  console.log('📚 Documentation Generator');
  console.log('═══════════════════════════════════════════');
  console.log('');

  if (flags.extensions)   generateExtensionCatalog();
  if (flags.protocols)    generateProtocolEncyclopedia();
  if (flags.sdks)         generateSdkReference();
  if (flags.architecture) generateArchitectureMap();

  console.log('');
  console.log('  ✅ Documentation generation complete');
  console.log('');
}

main();
