#!/usr/bin/env node
/**
 * Form Filler — headless Chromium via Playwright. Goes to a URL, fills a set
 * of selector->value fields, submits, and captures the resulting URL + a
 * screenshot. Useful for login flows, lead forms, or any repeated form
 * submission. Generated by the Aether Worker Foundry.
 *
 *   npm i playwright   # once
 *   node formfill.js --url https://example.com/login \
 *     --fields '{"#user":"me","#pass":"secret"}' --submit 'button[type=submit]'
 */
'use strict';
const fs = require('fs');

function arg(name, def) {
  const i = process.argv.indexOf('--' + name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

async function launch(chromium) {
  try { return await chromium.launch({ headless: true }); }
  catch (e) {
    const exe = process.env.PLAYWRIGHT_CHROMIUM || '/opt/pw-browsers/chromium';
    return await chromium.launch({ headless: true, executablePath: exe });
  }
}

(async () => {
  const { chromium } = require('playwright');
  const url = arg('url', '{{URL}}');
  const fields = JSON.parse(arg('fields', '{{FIELDS}}'));
  const submit = arg('submit', '{{SUBMIT_SELECTOR}}');
  const shot = arg('screenshot', 'result.png');

  const browser = await launch(chromium);
  const page = await browser.newPage();
  const result = { url, ok: false };
  try {
    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 30000 });
    for (const [selector, value] of Object.entries(fields)) {
      await page.fill(selector, String(value), { timeout: 10000 });
    }
    if (submit) {
      await Promise.all([
        page.waitForLoadState('networkidle', { timeout: 15000 }).catch(() => {}),
        page.click(submit, { timeout: 10000 }),
      ]);
    }
    result.ok = true;
    result.final_url = page.url();
    result.title = await page.title();
    if (shot) {
      await page.screenshot({ path: shot, fullPage: true });
      result.screenshot = shot;
    }
  } catch (e) {
    result.error = String(e.message || e);
  } finally {
    await browser.close();
  }
  console.log(JSON.stringify(result));
})().catch((e) => { console.error(e); process.exit(1); });
