#!/usr/bin/env python3
"""
Directory Sync Worker — watches a directory (content-hash based, no OS deps)
and uploads changed/new files to an HTTP endpoint. Survives restarts via a
state file of path->hash. Generated by the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, hashlib, json, os, sys, time
import urllib.request

STATE = ".filesync_state.json"


def file_hash(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def upload(endpoint, path, data):
    req = urllib.request.Request(
        endpoint, data=data, method="POST",
        headers={"Content-Type": "application/octet-stream",
                 "X-Filename": os.path.basename(path)})
    urllib.request.urlopen(req, timeout=60).read()


def scan(root):
    for dirpath, _, files in os.walk(root):
        for name in files:
            if name == STATE:
                continue
            yield os.path.join(dirpath, name)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="{{DIR}}")
    ap.add_argument("--endpoint", default="{{ENDPOINT}}")
    ap.add_argument("--interval", type=float, default={{INTERVAL}})
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()

    seen = {}
    if os.path.exists(os.path.join(a.dir, STATE)):
        try: seen = json.load(open(os.path.join(a.dir, STATE)))
        except Exception: pass

    while True:
        changed = 0
        for path in scan(a.dir):
            try:
                h = file_hash(path)
            except OSError:
                continue
            if seen.get(path) == h:
                continue
            try:
                with open(path, "rb") as f:
                    upload(a.endpoint, path, f.read())
                seen[path] = h
                changed += 1
                print(json.dumps({"uploaded": path})); sys.stdout.flush()
            except Exception as e:
                print(json.dumps({"upload_error": path, "detail": str(e)}), file=sys.stderr)
        try: json.dump(seen, open(os.path.join(a.dir, STATE), "w"))
        except OSError: pass
        if a.once:
            print(json.dumps({"done": True, "changed": changed}), file=sys.stderr)
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
