#!/usr/bin/env python3
"""
Disk Usage Monitor — walks a directory tree on an interval, tracks total size,
and fires a webhook when usage crosses a cap or grows by more than a threshold
between checks. Generated by the Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, os, sys, time
import urllib.request


def du(path):
    total = 0
    for dirpath, _, names in os.walk(path):
        for n in names:
            fp = os.path.join(dirpath, n)
            try:
                total += os.path.getsize(fp)
            except OSError:
                pass
    return total


def post(url, payload):
    req = urllib.request.Request(url, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"}, method="POST")
    urllib.request.urlopen(req, timeout=15).read()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="{{DIR}}")
    ap.add_argument("--cap-bytes", type=int, default={{CAP_BYTES}})
    ap.add_argument("--interval", type=int, default={{INTERVAL}})
    ap.add_argument("--webhook", default="{{WEBHOOK}}")
    ap.add_argument("--once", action="store_true")
    a = ap.parse_args()
    prev = None
    while True:
        size = du(a.dir)
        rec = {"dir": a.dir, "bytes": size, "cap_bytes": a.cap_bytes, "ts": time.time()}
        over_cap = a.cap_bytes > 0 and size > a.cap_bytes
        grew = prev is not None and size > prev
        if over_cap:
            rec["alert"] = "over_cap"
        if over_cap or (prev is None):
            print(json.dumps(rec)); sys.stdout.flush()
            if over_cap and a.webhook:
                try: post(a.webhook, rec)
                except Exception as e: print(json.dumps({"webhook_error": str(e)}), file=sys.stderr)
        elif grew:
            rec["grew_bytes"] = size - prev
            print(json.dumps(rec)); sys.stdout.flush()
        prev = size
        if a.once:
            break
        time.sleep(a.interval)


if __name__ == "__main__":
    main()
