#!/usr/bin/env python3
"""
Broken Link Checker — crawls a site same-domain and reports every link that
returns 4xx/5xx or times out, with the page it was found on. Generated by the
Aether Worker Foundry. Stdlib only.
"""
from __future__ import annotations
import argparse, json, re, sys, time
from collections import deque
from urllib.parse import urljoin, urlsplit, urldefrag
import urllib.request

_HREF = re.compile(r'href=["\']([^"\']+)["\']', re.I)


def head_or_get(url, timeout):
    for method in ("HEAD", "GET"):
        try:
            req = urllib.request.Request(url, method=method, headers={"User-Agent": "AetherLinkCheck/1.0"})
            with urllib.request.urlopen(req, timeout=timeout) as r:
                return r.status, r.read(500_000).decode("utf-8", "replace") if method == "GET" else ""
        except urllib.error.HTTPError as e:
            if method == "HEAD" and e.code in (403, 405):
                continue  # some servers refuse HEAD; retry with GET
            return e.code, ""
    return None, ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--start-url", default="{{START_URL}}")
    ap.add_argument("--max-pages", type=int, default={{MAX_PAGES}})
    ap.add_argument("--timeout", type=float, default=15.0)
    a = ap.parse_args()

    host = urlsplit(a.start_url).netloc
    seen_pages, checked, seq = set(), {}, deque([a.start_url])
    broken = 0
    pages = 0
    while seq and pages < a.max_pages:
        page = urldefrag(seq.popleft())[0]
        if page in seen_pages:
            continue
        seen_pages.add(page)
        status, html = head_or_get(page, a.timeout)
        pages += 1
        for m in _HREF.findall(html):
            link = urldefrag(urljoin(page, m))[0]
            if link in checked:
                st = checked[link]
            else:
                st, _ = head_or_get(link, a.timeout)
                checked[link] = st
                if urlsplit(link).netloc == host and link not in seen_pages:
                    seq.append(link)
            if st is None or st >= 400:
                broken += 1
                print(json.dumps({"broken": link, "status": st, "found_on": page}))
                sys.stdout.flush()
        time.sleep(0.2)
    print(json.dumps({"done": True, "pages": pages, "links_checked": len(checked), "broken": broken}), file=sys.stderr)


if __name__ == "__main__":
    main()
