#!/usr/bin/env python3
"""
Dedupe Worker — streams JSONL and drops duplicates by a key field (or the
whole record if no key is given), writing unique records to OUTPUT and a
summary of what was dropped to stderr. Generated by the Aether Worker Foundry.
Stdlib only.
"""
from __future__ import annotations
import argparse, json, sys


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default="{{INPUT}}")
    ap.add_argument("--output", default="{{OUTPUT}}")
    ap.add_argument("--key", default="{{KEY}}", help="field to dedupe on; empty = whole record")
    a = ap.parse_args()

    src = sys.stdin if a.input == "-" else open(a.input)
    dst = sys.stdout if a.output == "-" else open(a.output, "w")

    seen = set()
    total = kept = 0
    for line in src:
        line = line.strip()
        if not line:
            continue
        total += 1
        rec = json.loads(line)
        ident = json.dumps(rec.get(a.key), sort_keys=True) if a.key else json.dumps(rec, sort_keys=True)
        if ident in seen:
            continue
        seen.add(ident)
        kept += 1
        dst.write(json.dumps(rec) + "\n")

    if dst is not sys.stdout:
        dst.close()
    print(json.dumps({"total": total, "kept": kept, "dropped": total - kept}), file=sys.stderr)


if __name__ == "__main__":
    main()
